### ISSUE TITLE
Disable geonames interlinking for cities

### ISSUE THREAD

**Issue by rtroncy** [silknow/converter#1]
We attempted to use [https://github.com/DOREMUS-ANR/string2vocabulary/](String2Vocabulary) to match city and town names with Geonames URIs. However, the simple fuzzy matching strings are not efficient enough and this leads to a lot of linking mistakes, see also [this issue](https://github.com/DOREMUS-ANR/string2vocabulary/issues/4).

Meanwhile, I recommend to disable the usage of string2vocabulary for city names in the converter.

**Comment by pasqLisena** [comment]
Geonames matching is not managed by `string2vocabulary`, but by the official [Geonames package](https://www.geonames.org/source-code/javadoc/org/geonames/package-summary.html).

What it is possible to try is to better setting the language or the country. ([here](https://github.com/silknow/converter/blob/master/src/main/java/org/silknow/converter/commons/GeoNames.java) the unique entry point for SILKNOW)

Instead, if the errors are few, it is possible to manually fix the [mapping table](https://github.com/silknow/converter/blob/master/places.properties).
This map is automatically generated and updated for the new values. For values already in the map, it  acts as a cache.

**Comment by pasqLisena** [comment]
FYI, I corrected the id for Saint Etienne, so that it will correctly link to the [right city](http://www.geonames.org/2980291/saint-etienne.html) in next conversion

**Comment by rtroncy** [comment]
This has just amounted to add the line 281 of the [mapping table](https://github.com/silknow/converter/blob/master/places.properties)?

If so, we should just close this issue

**Comment by pasqLisena** [comment]
Yes, exactly
