### ISSUE TITLE
General: Improving Getty + SILKNOW Thesaurus linking

### ISSUE THREAD

**Issue by tschleider** [silknow/converter#10]
For strings not found in Getty, we should search for the SILKNOW thesaurus to get a new URI. For the strings not found in Getty and in SILKNOW, then we should maybe create a new URI (scheme to define).

**Comment by rtroncy** [comment]
You need to list the properties for which you will rely on the SILKNOW thesaurus to control the values. This will include, most likely, the material and the technique ... what else?

**Comment by tschleider** [comment]
Interlinking: addClassification (entity.java) tries to match ONLY with Silknow Thesaurus, addMaterial / addTechnique (production.java) ONLY with Getty

@pasqLisena : is this on purpose or an omission? I can try to fix it, just need some background information.

**Comment by tschleider** [comment]
Changed priority from Getty to Silknow Thesaurus, in case that a string can get matched with both.

**Comment by tschleider** [comment]
Need to split up strings to improve matching.

**Comment by tschleider** [comment]
Problem that still needs to be solved: why are some strings linked to weaving (Getty) instead of Weaving (SILKNOW) and similar issues. See the [stats slides](https://docs.google.com/presentation/d/1ch8WnzBTkgDjh2ybWHEPrNV8PT3A_moMGn6FDI_vSv4/edit#slide=id.g5b897345b9_0_136) for examples of different matches.

We also need to add in the SILKNOW Thesaurus the most common strings without link where appropriate.

**Comment by tschleider** [comment]
I looked into the "weaving" example and it has simply to do with the original json file having the string "woven" and getty having it as an alt label for "weaving" and our thesaurus entry does not. 

I will write an email to ask the domain experts to have a look.

**Comment by tschleider** [comment]
Since the last Thesaurus update I see a big improvement in terms of normalisation / precision of the matches that seems to address a lot of issues. If you can confirm @rtroncy based on the slides, I would close this here as a specific issue for now? (It started as a different problem long solved anyway)
