### ISSUE TITLE
General: Language information for strings missing in many cases

### ISSUE THREAD

**Issue by tschleider** [silknow/converter#11]
This information is mostly missing in the dataset, but we could quickly post-process it, e.g. the IMATEX dataset contains this information in the file names of the json, in most collections the location of the museum defines the language etc.

**Comment by rtroncy** [comment]
As a rule of thumb, most textual values should be represented with ```@language``` in RDF.

**Comment by tschleider** [comment]
Added tags now to most strings. This does not solve #24  of course. Example from 13975_en.ttl (imatex): 

ecrm:P3_has_note               "vellut tallat llavorat de 1 cos"@en ;
