### ISSUE TITLE
MTMAD: Image URIs only work after the record's main URI has been viewed before

### ISSUE THREAD

**Issue by tschleider** [silknow/converter#15]
We are not really using the URI to the record's main web page in the conversion, but if you click directly on the image URI (at least the one we crawl/convert) you receive a website with this message (5673.ttl/.json): 

"Votre session a expiré.
--
Vous allez être redirigé(e) automatiquement vers la page de connexion.Si rien ne se passe d'ici 5 secondes, veuillez cliquer sur le lien ci-dessous."

URI: http://www.mtmad.fr/floracci/servlet/PhotoManager?recordId=musee:MUS_PHOTO:148934&idocsId=ged:IDOCS:164523&resolution=MEDIUM&timeStamp=1372753552391&imageScale=L396

The main URI for this record is (after clicking on it, the first link should work in the same browser session): 
http://www.mtmad.fr/floracci/jsp/opac/opac_index.jsp?action=view_notice&recordId=musee:MUS_BIEN:5673&only_main=true&lang=fre-FR

**Comment by rtroncy** [comment]
This [record](http://www.mtmad.fr/floracci/jsp/opac/opac_index.jsp?action=view_notice&recordId=musee:MUS_BIEN:5673&only_main=true&lang=fre-FR) has apparently 4 illustrative images. Are we capturing them all?

This [link](http://www.mtmad.fr/floracci/servlet/PhotoManager?recordId=musee:MUS_PHOTO:148934&idocsId=ged:IDOCS:164523&resolution=MEDIUM&timeStamp=1372753552391&imageScale=L396) corresponds to the third image. It seems to me that the main problem is that this is not a permalink (but a link based on some session id stored in some cookies).

@ehrhart Can you indeed investigate how to crawl the permalinks of images for this museum?

**Comment by ehrhart** [comment]
These are already permalinks, but a valid session is required to view them, and there doesn't seem to be a way around it.

**Comment by rtroncy** [comment]
Therefore, an alternative for this museum source, is to not rely on the session-based hosting of the images but rather use local copies. @tschleider Can you implement this as a workaround?

**Comment by tschleider** [comment]
@ehrhart : thanks for looking into this!
@rtroncy : yes, that is my plan to do this with all local copies for all dataset anyway, but I hoped we could also have less confusing links to the original. Shall I close this here now or only once I added all the local URIs to the graph?

**Comment by rtroncy** [comment]
Close this issue only when local image links (for this source) will be present in the graph

**Comment by tschleider** [comment]
Keeping https://github.com/silknow/crawler/issues/8 in mind, it is solved on the converter side. The "original" links are dead now, but we can construct the local silknow URIs with the last crawl thanks to @ehrhart  script.

We cannot test them though, because we also need to ask @javier-sevilla  to reupload @ehrhart  's new crawl to the media server! Thanks in advance!

Test links: 
http://silknow.org/silknow/media/mtmad/149_0.jpg   (149.json)
http://silknow.org/silknow/media/mtmad/149_1.jpg   (149.json)
http://silknow.org/silknow/media/mtmad/50967_2.jpg (50967.json)

**Comment by javier-sevilla** [comment]
Dear Thomas

The mtmad files are updated in the server. Now the links work.

Javier.

**Comment by tschleider** [comment]
In general this works now, but some links are still dead (it's reconverted and online now):

http://silknow.org/silknow/media/mtmad/1004_3.jpg

[Query](http://data.silknow.org/sparql?default-graph-uri=&query=prefix+crmdig%3A+%3Chttp%3A%2F%2Fwww.ics.forth.gr%2Fisl%2FCRMext%2FCRMdig.rdfs%2F%3E++%0D%0Aprefix+crmsci%3A+%3Chttp%3A%2F%2Fwww.ics.forth.gr%2Fisl%2FCRMsci%2F%3E%0D%0A%0D%0ASELECT+DISTINCT+%3Fid+%3Fobj+%3Furl+%0D%0AWHERE+%7B%0D%0A%0D%0A++GRAPH+%3Chttp%3A%2F%2Fdata.silknow.org%2Fmtmad%3E+%7B%0D%0A%0D%0A+++++%3Fdig+a+crmdig%3AD1_Digital_Object+.+%7D%0D%0A+++++%3Fdig++ecrm%3AP129_is_about+%3Fimg+.%0D%0A++++++%3Fimg+a+ecrm%3AE38_Image+.%0D%0A++++++%3Fimg+schema%3AcontentUrl+%3Furl+.%0D%0A%0D%0A%0D%0A++++++%3Fdig+ecrm%3AP129_is_about+%3Fobj+.%0D%0A++++++%3Fobj+a+ecrm%3AE22_Man-Made_Object+.%0D%0A++++++%3Fobj++dc%3Aidentifier+%3Fid+.%0D%0A%0D%0A%0D%0A%7D&format=text%2Fhtml&timeout=0&debug=on)

**Comment by tschleider** [comment]
Ok, this is more of a crawling issue, as this image simply has not been crawled and could not have been uploaded by @javier-sevilla (the links all work, and it's url is correctly stated in the JSON and finally the converted TTL)

**Comment by tschleider** [comment]
Finally fixed, thanks @ehrhart  for looking into the crawler again!

**Comment by rtroncy** [comment]
Are all media (local) links now working or does @javier-sevilla need to copy more images to http://silknow.org/silknow/media/mtmad/?

**Comment by tschleider** [comment]
No, it was a crawler issue and Thibault fixed it. All local URIs are
working now, as far as I could see.
