### ISSUE TITLE
String2Vocubulary not used for techniques

### ISSUE THREAD

**Issue by tschleider** [silknow/converter#17]
I am testing right how to imitate the getty/thesaurus linking ( https://github.com/DOREMUS-ANR/string2vocabulary ) to work with the "techniques" fields the same way as it is implemented for the "materials" fields.  

Once it works I will re-convert and re-upload all datasets/TTL files.

**Comment by rtroncy** [comment]
Thanks @tschleider ! Try to mention issue number when doing commits so github automatically associates commits with issues which serve as justification as why issues are closed
