### ISSUE TITLE
Missing texts present in the original JSON files but not yet converted in the KG

### ISSUE THREAD

**Issue by tschleider** [silknow/converter#18]
This can be further used for text analysis / extraction

**Comment by rtroncy** [comment]
It would be good to provide examples, for each source, of what textual information has not yet been converted as well as the reason for it (e.g. missing mapping)

**Comment by tschleider** [comment]
Ok, I went through every field mentioned in https://docs.google.com/document/d/1HbWXAuDX0TNXGec0sgVLRiQ5G0DxLBNiTsn2gWqcWGc/edit and only "Related Objects" of MET and "Related" of RISD are not included in some way. The former is related to #4 and for the latter I need some clarification from @mpuren  or Pierre, I commented it accordingly. 

What is also missing is most fields of MTMAD, see #9

**Comment by tschleider** [comment]
The format of MET and Joconde websites/api/crawler changed and some information from their new formats is not integrated into the converter yet. Both converters need another overhaul.

**Comment by tschleider** [comment]
This was more of a reminder to update the mapping, which has been done, but the mapping has changed since, suggest to close and continue as part of #56.
