### ISSUE TITLE
MFA/Joconde/MAD: One field instead of two for Material and Technique

### ISSUE THREAD

**Issue by tschleider** [silknow/converter#21]
Right now it's converted as "material" field only, but this is of course not sufficient.

**Comment by tschleider** [comment]
Including MAD/Les arts decoratifs here.

**Comment by tschleider** [comment]
Possible solution: get the linking done before the mapping and map it accordingly afterwards

**Comment by tschleider** [comment]
I realised I cannot do this until the Silknow Thesaurus differentiates clearly between Technique and Material in a machine readable way.

**Comment by rtroncy** [comment]
What concrete actions do you recommend to the thesaurus maintainer? To create high level concepts so that the thesaurus either branches in material or branches in techniques? Is it not already the case thanks to the hook to Getty?
