### ISSUE TITLE
Imatex: Language confusion

### ISSUE THREAD

**Issue by tschleider** [silknow/converter#22]
This is the only dataset with different languages and there is some confusion in the original dataset, also because we have several files per record. We need some more checks and implement some ways to correct/avoid them in the graph.

**Comment by tschleider** [comment]
To clarify, these language problems can be sub-divided into 2 smaller problems:

1) Imatex is the only dataset that we have used so far with different languages. Each records has 2-3 files in English, Spanish, Catalan and our converter is supposed to interlink all their information to one common object. Right now this is not the case. To check what I mean try searching for both "3008_en" and "3008_es" at http://data.silknow.org/fct/ to see that these are two different entities in the graph, which should not be the case.

2) The original Dataset is already not consisent. The original language seems to be Catalan, but for some fields in the English version there is either still Catalan text or even a mix between Catalan and English. E.g.  first object when looking for textile pieces in the English version on their website ( Reg. nr. 108), here an example: 

TÈCNICA* | brocaded -  / brocading weft -  / trama llançada -  / patterned fabric -

http://imatex.cdmt.cat/_cat/pubindex.aspx

**Comment by pasqLisena** [comment]
I see that there is a huge problem with this object:
http://data.silknow.org/object/f9287b4f-da28-305f-9b1a-9b594cc144f9

This  is target of a lot of properties (clearly a bug)

**Comment by pasqLisena** [comment]
The source files had a weird translation in the fields with the id, which was `REGISTER NUMBER` in en, `NUM. REGISTRE` in ca, and `NÚM.REGISTRO` in es.
The converter was failing in extracting this id in not-English languages, so that the id for all files in ca and es was the string `null`.

This is the only case of translated field key. (so that `CRONOLOGIA` is always `CRONOLOGIA` in all languages).

**Comment by tschleider** [comment]
@pasqLisena  thanks for the bug fix, I will reopen it again because of the second issue that just needs to be highlighted somewhere until somehow addressed.

**Comment by tschleider** [comment]
Created #24 for remaining issue.
