### ISSUE TITLE
Garin: Problem with assignment of crmdig:D1_Digital_Object 

### ISSUE THREAD

**Issue by tschleider** [silknow/converter#23]
The query:
```
SELECT  ?dig 
WHERE {
  GRAPH <http://data.silknow.org/garin> {
     ?dig a crmdig:D1_Digital_Object . }
}
```
[results](http://data.silknow.org/sparql?default-graph-uri=&query=SELECT++%3Fdig+%0D%0AWHERE+%7B%0D%0A++GRAPH+%3Chttp%3A%2F%2Fdata.silknow.org%2Fgarin%3E+%7B%0D%0A+++++%3Fdig+a+crmdig%3AD1_Digital_Object+.+%7D%0D%0A%7D+&format=text%2Fhtml&timeout=0&debug=on)

should return one row for every Garin record. We found out that something is wrong with the class assignment.

**Comment by pasqLisena** [comment]
This issue is not replicable in current status of the converter.

I think we already fixed this behaviour [here](https://github.com/silknow/converter/commit/e739f322ff9db7104cc347342522d047614c475b#diff-efb7f4fa9755604398ebbdff0b7188f6R122) and we just need to re-upload the data.

**Comment by tschleider** [comment]
I reconverted it and it seems fixed. Have not uploaded it yet, but will close it once done (and working).
