### ISSUE TITLE
VAM: "Summary" field / "public_access_description" needs to be split up in different fields

### ISSUE THREAD

**Issue by tschleider** [silknow/converter#28]
We do have mappings for the fields "Subject depiction" e.g., but right now this and other ones are part of a huge text block in the field "public_access_description" which corresponds to "Summary" on the website.  Due to the original data being in this bad format it needs to be split up and converted according to the existing mapping.

Here an example from O10418.json, the unedited value of the field:

"<b>Object Type</b><br>This embroidered band may have been used as a ribbon, intended for decorating or fastening clothes, or as the type of trimming known in the 16th and 17th centuries as a guard. Guards were decorative bands of rich material that were used as borders to conceal the seams on clothing.<br><br><b>Materials & Making</b><br>The ribbon has been made from a narrow piece of silk satin cut on the cross, which was possibly an offcut from the construction of a garment. Its colour was originally a rich purple, now faded on the front side. Its edges have been turned and slashed, in keeping with the fashionable practice at the time of cutting decorative slits into fabric. The pattern has been built up with a variety of stitches, knots and couched cords (corded thread laid down on the fabric and held down by stitching).<br><br><b>Subjects Depicted</b><br>Elizabeth I (ruled 1558-1603) was depicted in gowns decorated with embroidered eyes and ears in at least two portraits. In Elizabeth's case, the symbolism may have been intended to suggest ideas of Fame, the Art of Governmen or religious faith. But the combination of weeping eye and pierced heart on this ribbon makes an association with matters of love more likely."

**Comment by rtroncy** [comment]
The `ecrm:P3_has_note` values attached to the object from this museum are a perfect candidate to try extensively Wikifier, see also #63.

Note: the object referenced above is http://data.silknow.org/object/a4e34366-4967-3c78-a3e8-69e965f0a1f0

**Comment by rtroncy** [comment]
Close since we have issue #63
