### ISSUE TITLE
Time periods: String replacement / linking with Getty AAT / Perio.do

### ISSUE THREAD

**Issue by tschleider** [silknow/converter#3]
Web: https://perio.do/en/

**Comment by tschleider** [comment]
@AvgustinKastelic 
Could you give me a status update for the handover?

**Comment by tschleider** [comment]
@rtroncy 
@pasqLisena  and me tried to extend the string2vocabulary mechanism we have for the SILKNOW, Getty and Geonames thesaurus to Perio.do and in general it works. We do, however, have some limitations due to perio.do itself. I will generate a list with most common strings in our KG, also labelled by language and ask them to create a few more time periods according to this, because otherwise there are too few data points and they are mostly not labelled by language. 

Example where it works already (not online yet) from IMATEX, 13952_en.ttl:

Original ttl from field:   "16th century -  / 17th century -"

```ttl
<http://data.silknow.org/production/e644bed4-086b-30ce-a797-09d06638fbb8>
        a                       ecrm:E12_Production ;
        ecrm:P108_has_produced  <http://data.silknow.org/object/d8bdaaa5-b7fd-302f-aba2-737c4f396556> ;
        ecrm:P126_employed      <http://data.silknow.org/vocabulary/368> ;
        ecrm:P32_used_general_technique
                "weaving technique"@en , "trama llançada"@en ;
        ecrm:P4_has_time-span   <http://n2t.net/ark:/99152/p086kj97q3t> , <http://n2t.net/ark:/99152/p086kj9t437> ;
...
```

**Comment by rtroncy** [comment]
As we have discussed, this approach will ultimately not be suitable in numerous cases, since, in your concrete example, the URIs http://n2t.net/ark:/99152/p086kj97q3t and http://n2t.net/ark:/99152/p086kj9t437 refer to respectively the 16th and 17th century in South Carolina! perio.do seems to be lacking encompassing periods, since it always tries to bind one with a geographical area, which makes less sense when describing centuries.

Hence, we should rather rely on Getty AAT that provides such notions of generic period. For example, 16th century will be http://vocab.getty.edu/aat/300404510

**Comment by tschleider** [comment]
We made some progress here as it now (almost) works out of the box with Getty AAT, @pasqLisena  works on an update of string2vocabulary for that. 

However, time periods are exclusively English on Getty AAT. Our solution is to create a local copy and modify it to include Italian, Spanish and French translations of the most common periods as skos:altLabels for now. 

In the long-term we should suggest these labels to Getty to include them officially maybe?

**Comment by rtroncy** [comment]
Yes, this is an excellent idea! To progress on the translation, you should output a CSV containing all the English period names found in the data. Then, load this CSV in a google spreadsheet so our experts from UVEG, UNIPA and CNRS can help in the translation.

**Comment by tschleider** [comment]
We need to consider other options to parse time expressions instead of matching them with an vocabulary.

**Comment by tschleider** [comment]
Just an internal reminder to extend the labels to more centuries (e.g. 13th century)

**Comment by tschleider** [comment]
Overhaul with Wikidata Reconciliation necessary:
https://wdreconcile.toolforge.org/en/api

**Comment by rtroncy** [comment]
See also https://github.com/schemaorg/suggestions-questions-brainstorming/issues/219 and around for handling uncertain dates

**Comment by pasqLisena** [comment]
And how we manage uncertainty on DOREMUS: http://data.doremus.org/artist/e8e2694f-ead1-3d37-8895-2473a25f9858/birth/interval

**Comment by rtroncy** [comment]
Closing since we have now #66.
