### ISSUE TITLE
Enable linked data dereferencing for UNIPA objects

### ISSUE THREAD

**Issue by rtroncy** [silknow/converter#31]
The UNIPA dataset has been recently integrated in the knowledge graph, but we cannot dereference URIs like http://data.silknow.org/UNIPA/MONREALE2 and we have to go through the 'describe' version (http://data.silknow.org/describe/?url=http%3A%2F%2Fdata.silknow.org%2FUNIPA%2FMONREALE2).

The resolution is simple: just add the corresponding rule in the configuration

**Comment by pasqLisena** [comment]
The URI has been dereferenced. I also updated the internal documentation about URI dereferencing
