### ISSUE TITLE
'assestment' instread of 'assessment' in the URI generated for GARIN

### ISSUE THREAD

**Issue by rtroncy** [silknow/converter#32]
See: http://data.silknow.org/assestment/65aa4e90-2891-3f4c-98c8-afc9c8a99060 which obviously be http://data.silknow.org/assessment/65aa4e90-2891-3f4c-98c8-afc9c8a99060 ... linked from
http://data.silknow.org/object/9ca5ecba-5406-306d-b293-1c7c33eea53d.

This mistake is true for GARIN at least.

**Comment by pasqLisena** [comment]
I keep the issue open as reminder for enabling disambiguation for `assessment` and disabling for `assestment`

**Comment by tschleider** [comment]
@pasqLisena  Thanks for the commit, but I do not completely understand if there is anything left to do?

**Comment by rtroncy** [comment]
Well, it seems there are still problems.
- You need to make sure that you have a http redirection rules for /assessment (and not assestment) for the linked data URIs
- You should grep in your dumps whether you have occurrences of 'assestment' or not and make sure they all disappear. I can still dereference http://data.silknow.org/assestment/65aa4e90-2891-3f4c-98c8-afc9c8a99060 which is obviously wrong.

**Comment by pasqLisena** [comment]
Yes, I add the re-conversion of the whole dataset

**Comment by tschleider** [comment]
As far as I can see the ones from GARIN disappeared, but it also existed in Imatex, which conversion is still ongoing.

**Comment by tschleider** [comment]
I cannot see any "assestment" anymore whatsoever, therefore close.
