### ISSUE TITLE
Image links for the UNIPA dataset are blank nodes

### ISSUE THREAD

**Issue by rtroncy** [silknow/converter#33]
For example, this UNIPA record http://data.silknow.org/object/48821af1-ee38-3eea-8b43-dfe3527e7653 points to 5 different illustrative images:
* http://data.silknow.org/image/70de6eac-c57b-3b6b-bb00-ffa38530ce6a
* http://data.silknow.org/image/dc659e21-db04-3128-a529-0887f5353c12
* http://data.silknow.org/image/b93618fe-eccd-3315-8eb9-daf2f85ea23f
* http://data.silknow.org/image/629d3d02-a6aa-3596-8ab5-370ef83c835c
* http://data.silknow.org/image/b9c744d8-9dde-3ff4-8525-15821af926d9
but each of them points to a blank node.

The value of the `schema:contentURL` property should be replaced by `http://silknow.org/media/unipa/` + the value of the `dc:identifier` property of the E38_Image object. 

Note: the source for getting this part of the graph is at https://docs.google.com/spreadsheets/d/1DpByr7e3rmtnSktxoASZ5VKte-KpurwxelVNtQxl6yA/edit#gid=0. Unfortunately, this spreadsheet does not tell us which images we should take from https://silknow.uv.es/owncloud/index.php/apps/files/?dir=/UNIPA&fileid=43. It is unclear, for me, why those 5 images have been selected. @pasqLisena can you answer this from the code?

**Comment by pasqLisena** [comment]
(sorry I referred the wrong commit here)

**Comment by pasqLisena** [comment]
I keep this issue open because we need to test (tomorrow?) the existence of this kind of files:
- http://silknow.org/silknow/media/unipa/mudipa1.4.jpg
- http://silknow.org/silknow/media/unipa/mudipa1.jpg

I include here also a reference to issue #13 

> Unfortunately, this spreadsheet does not tell us which images we should take from https://silknow.uv.es/owncloud/index.php/apps/files/?dir=/UNIPA&fileid=43.

There is a field called `Images (names of the images in the document)`

**Comment by tschleider** [comment]
It's not reconverted and uploaded, yet, but the implementation is tested and works.

Two problems remain: the links still do not always work ( #13 ) and the (manual) curation of the UNIPA dataset is not unified, so the values of the field "Images" is not always the same. I sent an email about this to Georgia and she is working on it.
