### ISSUE TITLE
VAM, GARIN, JOCONDE: intermediary node missing in the knowledge graph?

### ISSUE THREAD

**Issue by rtroncy** [silknow/converter#34]
For VAM, test the following [query](https://github.com/silknow/api/blob/master/queries/wp3/VAM)  (and add a LIMIT 10). One observes that the variable `obj` is sometimes an object (`E22 Man-Made Object`) and sometimes an image (`E38 Image`). Is this the symptom that a node is missing in the knowledge graph? This has to be checked from the converter code and the [mapping files](https://drive.google.com/drive/folders/1CkYfI3Vf12z5a0Gf46und_EV02odAees)

The GARIN dataset has the same issue. 

For JOCONDE, test the following (query)(https://github.com/silknow/api/blob/master/queries/wp3/JOCONDE) (and add a LIMIT 10). One again observes that the variable `obj` is sometimes an object (`E22 Man-Made Object`) and sometimes a document (`E31 Document`). Again, is this the symptom that a node is missing in the knowledge graph?

**Comment by pasqLisena** [comment]
This is not a problem with the data, but with the query.

These are the lines involving the `?obj`:


```sparql
SELECT DISTINCT ?id ?obj ...
WHERE {
  GRAPH <http://data.silknow.org/vam> {
     ?dig a crmdig:D1_Digital_Object . }
  ...
  ?dig ecrm:P129_is_about ?obj .
  ?dig ecrm:P129_is_about ?prd .
 ...
  ?obj  dc:identifier ?id .
}
```

Looking at this, the results of the query are correct, because a Digital Object may describe both a MMO and an Image.

On my opinion, what is missing in the query is a typecast: `?obj a ecrm: E22_Man-Made_Object`.

For GARIN and JOCONDE, same story. The only difference are some OPTIONAL (so not impacting).

**Comment by rtroncy** [comment]
Right! Can you update the queries accordingly at https://github.com/silknow/api/tree/master/queries/wp3 (by adding an additional constraint on the type of the object)?

**Comment by pasqLisena** [comment]
The queries are ok now.
Btw, there is any reason for which the query files have no extension at all (rather than being `.rq` or `.sparql`)? cc @tschleider

**Comment by rtroncy** [comment]
No, I wanted to make the same observation to @tschleider. Please, add the `.sparql` extension to all filenames. I would also lowercase all filenames (my taste)

**Comment by pasqLisena** [comment]
Ok, everything is fixed here
