### ISSUE TITLE
Geonames: Interlinking with St. Etienne is (still) wrong

### ISSUE THREAD

**Issue by tschleider** [silknow/converter#36]
Link goes sometimes to Saint-Étienne-du-Rouvray (http://sws.geonames.org/2980236/)  instead of Saint-Etienne (http://www.geonames.org/2980291/) 

[Query showing all place names belonging to France](http://data.silknow.org/sparql?default-graph-uri=&query=SELECT+distinct+%3Fplace+count%28distinct+%3Fs%29+as+%3Fcount%0D%0AWHERE+%7B%0D%0A++++++%3Fs+a+ecrm%3AE12_Production+.%0D%0A+%0D%0A%0D%0A+%7B+%3Fs+ecrm%3AP8_took_place_on_or_within+%3Fl%0D%0A+++++%7B+SELECT+%3Fl+SAMPLE%28%3Floc%29+as+%3Fplace%0D%0A++++++++++WHERE+%7B+%3Fl+geonames%3Aname+%3Floc+.%0D%0A+++++++++++++++++++%3Fl+geonames%3AcountryCode+%22FR%22%7D%0D%0A+++++++%7D+.+FILTER%28isIRI%28%3Fl%29%29+%7D%0D%0A%0D%0A%3Fl+geonames%3AcountryCode+%22FR%22%0D%0A%0D%0A%0D%0A%0D%0A%7D%0D%0AGROUP+BY+%3Fplace%0D%0AORDER+BY+DESC+%28%3Fcount%29%0D%0A%0D%0A%0D%0A%0D%0A%0D%0A%0D%0A%0D%0A%0D%0A%0D%0A%0D%0A%0D%0A%0D%0A&format=text%2Fhtml&timeout=0&debug=on)

See also https://github.com/DOREMUS-ANR/string2vocabulary/issues/4

**Comment by pasqLisena** [comment]
This is as easy as replacing every occurrence of the bad `2980236` to the correct `2980291` in [places.properties](https://github.com/silknow/converter/blob/master/places.properties), which contains the mapping label -> geonames id (or -1 if missing).

I included this replacement into commit e9e10d6.

Moreover, I added a final trimming to the place labels (so that we have not anymore trailing spaces)

**Comment by rtroncy** [comment]
Thanks @pasqLisena !

@tschleider This only impacts Joconde according to this [query](http://data.silknow.org/sparql?default-graph-uri=&query=SELECT+distinct+%3Fg+%3Fplace+count%28distinct+%3Fs%29+as+%3Fcount%0D%0AWHERE+%7B%0D%0A++graph+%3Fg+%7B%0D%0A++++++%3Fs+a+ecrm%3AE12_Production+.%0D%0A++%7D%0D%0A++%7B+%3Fs+ecrm%3AP8_took_place_on_or_within+%3Fl%0D%0A+++++%7B+SELECT+%3Fl+SAMPLE%28%3Floc%29+as+%3Fplace%0D%0A++++++++++WHERE+%7B+%3Fl+geonames%3Aname+%3Floc+.%0D%0A+++++++++++++++++++%3Fl+geonames%3AcountryCode+%22FR%22%7D%0D%0A+++++%7D+.+FILTER%28isIRI%28%3Fl%29%29+%7D%0D%0A++%3Fl+geonames%3AcountryCode+%22FR%22%0D%0A%7D%0D%0AGROUP+BY+%3Fg+%3Fplace%0D%0AORDER+BY+DESC+%28%3Fcount%29%0D%0A&format=text%2Fhtml&timeout=0&debug=on). Please, reconvert and upload Joconde and close this issue.

**Comment by tschleider** [comment]
I reconverted Joconde (which goes very quickly) but it actually concerns VAM. Will reconvert VAM then, too.

**Comment by tschleider** [comment]
Solved. Check the query again: [Query showing all place names belonging to France](http://data.silknow.org/sparql?default-graph-uri=&query=SELECT+distinct+%3Fplace+count%28distinct+%3Fs%29+as+%3Fcount%0D%0AWHERE+%7B%0D%0A++++++%3Fs+a+ecrm%3AE12_Production+.%0D%0A+%0D%0A%0D%0A+%7B+%3Fs+ecrm%3AP8_took_place_on_or_within+%3Fl%0D%0A+++++%7B+SELECT+%3Fl+SAMPLE%28%3Floc%29+as+%3Fplace%0D%0A++++++++++WHERE+%7B+%3Fl+geonames%3Aname+%3Floc+.%0D%0A+++++++++++++++++++%3Fl+geonames%3AcountryCode+%22FR%22%7D%0D%0A+++++++%7D+.+FILTER%28isIRI%28%3Fl%29%29+%7D%0D%0A%0D%0A%3Fl+geonames%3AcountryCode+%22FR%22%0D%0A%0D%0A%0D%0A%0D%0A%7D%0D%0AGROUP+BY+%3Fplace%0D%0AORDER+BY+DESC+%28%3Fcount%29%0D%0A%0D%0A%0D%0A%0D%0A%0D%0A%0D%0A%0D%0A%0D%0A%0D%0A%0D%0A%0D%0A%0D%0A&format=text%2Fhtml&timeout=0&debug=on)
