### ISSUE TITLE
General: "Type of object" information / type assignment

### ISSUE THREAD

**Issue by tschleider** [silknow/converter#37]
WP4 cannot use all types of objects, so they would like a query that filters out e.g. furniture and other objects that are not pure fabrics.

We do have `ecrm:E17_Type_Assignment` whose `ecrm:P42_assigned` properties get linked to the thesaurus, e.g. `10230000731.ttl` (Joconde) has 

```ttl
<http://data.silknow.org/object/a48bedc7-6792-313f-9478-0dfd91353603/type_assignment/1>
         a                    ecrm:E17_Type_Assignment ; 
         ecrm:P2_has_type     "Domaine"@fr ;
         ecrm:P41_classified  <http://data.silknow.org/object/a48bedc7-6792-313f-9478-0dfd91353603> ; 
         ecrm:P42_assigned    <http://vocab.getty.edu/aat/300014063> .
``` 

The usefulness of this needs to be tested and confirmed, eventually extended or we should look into other possibilities to isolate this type of information.

**Comment by tschleider** [comment]
With 
```
SELECT distinct count(?s) as ?count  ?link
WHERE {
      ?s a ecrm:E17_Type_Assignment .
      ?s ecrm:P42_assigned ?link .
}
GROUP BY  ?link
ORDER BY DESC (?count)
```

I get these [results](http://data.silknow.org/sparql?default-graph-uri=&query=%0D%0A%0D%0A%0D%0ASELECT+distinct+count%28%3Fs%29+as+%3Fcount++%3Flink%0D%0AWHERE+%7B%0D%0A%0D%0A+%0D%0A++++++%3Fs+a+ecrm%3AE17_Type_Assignment+.%0D%0A%0D%0A++++++%3Fs+ecrm%3AP42_assigned+%3Flink+.%0D%0A%0D%0A%0D%0A%0D%0A%7D%0D%0AGROUP+BY++%3Flink%0D%0AORDER+BY+DESC+%28%3Fcount%29%0D%0A%0D%0A%0D%0A&format=text%2Fhtml&timeout=0&debug=on), which is maybe a promising start! This means we can already look for textiles with queries, and will filter out quite many non-textiles, e.g. furnitures. I think to improve this we need some progress on #35 , which means we could pre-filter E17_Type_Assignment to only include "Domains" e.g. But we can see that quite many objects are actually getting matches with our Thesaurus and Getty already! So maybe there is potential to discuss this aspect of the Thesaurus internally.

**Comment by tschleider** [comment]
@rtroncy : I created a sheet to have an overview here, too. [Link ](https://docs.google.com/spreadsheets/d/1pYT9ExzYgOb6gs7xzyNXAZuVOHFCTWG2baAZaeJhlRU/edit#gid=0)

The tabs show all the cases of links with Getty AAT and all the cases of strings that could not be matched so far. I would suggest to deactivate the Getty AAT linking for the next reconversion to have a better overview about the actual raw strings.

Either way, we need to decide how to make progress here. Shall we also locally modify our Getty AAT export TTL by adding altLabels to existing nodes, or create our own controlled dictionary? Should we aim at "normalising" the domains as much as possible to have useful big categories for our research (like "textiles" and "non-textiles" etc.) or aim at keeping as much fine-grained information as possible?

**Comment by rtroncy** [comment]
A lot of progress has been done on this issue, in particular, thanks to the new [categories controlled vocabulary](https://github.com/silknow/knowledge-base/blob/master/vocabularies/category/categories.ttl). I will close this issue in favor of opening a new one to solve the now JOKER and BATMAN problem.
