### ISSUE TITLE
UNIPA: update the converter for 'warp', 'weft' and 'construction'

### ISSUE THREAD

**Issue by rtroncy** [silknow/converter#39]
@tschleider Can you please update the UNIPA converter since the mappings have been updated tonight (see https://docs.google.com/document/d/1acGECbA7AE8CS8b8ZG5JROZSyyWYTCW-IW7jYYfgIPQ/edit#). In particular, the fields 'warp' and 'weft' now describe materials and 'construction' and 'tecnic' describe techniques.

**Comment by tschleider** [comment]
It's implemented and needs to be reconverted. According to the mapping file a new path has been added to all the mentioned fields, but the old one is still in the google doc, therefore I implemented it exactly like this.

**Comment by rtroncy** [comment]
@tschleider Your message is not clear since it is not obvious to know what is old and what is new. Can you point out precisely what the implementation looks like now and why you think the previous preserved path mappings are overlapping or causing a problem (if any)?

**Comment by tschleider** [comment]
@rtroncy : For 'weft' the Google doc says this for path, which are actually two paths, so i just added a rule in the code:

S4_Observation 08 observed E22_Man-Made Object
S4_Observation P3 has note E62_String
S4_Observation P2 has type E55_Type (Trama)
S4_Observation P14 carried out by E39_Actor P131 is identified by E82_Actor Appellation (Roberta Civiletto)

E12_Production P106 has produced E22_Man-Made Object
E12 Production P126 employed E57_Material (seta)

**Comment by tschleider** [comment]
Actually I think we misunderstood something here, according to some mapping notes, Marie is suggesting to map the substring "seta" as material, which is just one word in the textual field "weft", so it's not the whole field. It's a bit confusing, I tried to comment on it in the mapping documents. Compare the mapping docs for CERES e.g. https://docs.google.com/document/d/1qecnBVqxtTQ5GC4LRITixGdiLFf4zB6824B882zUgbg/edit?ts=5df9f994#

**Comment by rtroncy** [comment]
Indeed, clarifications are needed, in particular if this requires a complex interpretation of this field value. Please, update this issue after your call.

**Comment by tschleider** [comment]
We agreed to leave one path only per field, but to store possible more detailed paths (once entities can be linked) for the future in another document ( https://docs.google.com/spreadsheets/d/1Zn7KDB6nsx7YuYLokw5qyepp8ekONYfS8Oyr_IXrOac/edit#gid=0 ).

Therefore there are no new mappings for UNIPA to be implemented and this issue can be closed. In general there are still mappings not reflected in the KG, though, for probably not only one dataset. But this is more part of #18

**Comment by rtroncy** [comment]
@tschleider Can you create a new issue for the case where a given metadata input field needs more complex processing since it typically contains mixed information (e.g. material and technique) yielding different paths in the graph? You could use https://docs.google.com/spreadsheets/d/1Zn7KDB6nsx7YuYLokw5qyepp8ekONYfS8Oyr_IXrOac/edit#gid=0 as the basis.
