### ISSUE TITLE
METConverter: Field "galleryInformation" not mapped / mapping not implemented yet

### ISSUE THREAD

**Issue by tschleider** [silknow/converter#4]
Awaiting input for how to deal with "relatedObjects" and the field "galleryInformation"

**Comment by tschleider** [comment]
@mpuren @rtroncy  Pierre spoke about the "galleryInformation" field during the Telecon on May 24 and there was no objection to the opinion of ignoring/removing this field because it is irrelevant to SILKNOW, can you confirm this?

**Comment by rtroncy** [comment]
@tschleider Can you provide a concrete example in this thread, with the json object corresponding to the record from MET highlighting the field `galleryInformation` that could be ignored?

**Comment by tschleider** [comment]
@rtroncy  

02.12.json excerpt: {"label":"galleryInformation","value":"Not on view"} 

See also our comments at the mapping doc: 
https://docs.google.com/document/d/1hey3yfQf4Se_N2jVi4bjgwHNb2-_pCBm4l5A2eEf_gk/

**Comment by rtroncy** [comment]
Regarding the `galleryInformation` field, it provides information whether the object is on display in the museum or if it is hidden in some storage room? If so, I agree that this is not necessarily an information we need to materialize in the triple store. Out of curiosity, I'm curious to know the ratio of the number of objects which are "Not on view" versus the ones displayed in the museum (what is the other possible value)?

Regarding the `Related objects`, the value is always a long text describing potentially multiple objects? In the example, one can see the name of a Work, the details about the artist, a short description of the Work and some information on where to find the object in the museum. Is this specific to the MET or consistent across museums?

**Comment by mpuren** [comment]
Hi @tschleider, I've added a comment in the Gdoc concerning the 'galleryInformation' field, and I think we can remove it. I wait for Pierre to confirm.

**Comment by tschleider** [comment]
"galleryInformation": I updated the stats on the Google Drive:

https://docs.google.com/spreadsheets/d/1Pmk3B09lzsSBR1jq7stw0HPtT7deOwTxYYXC_dIxCPc/edit#gid=1246324626

401 out of 8364 have a specific information in that field (it used to be way less last year, but they updated their data). So the ratio is around 0,5%. I think Pierre is in favour to keep this field, but the mapping is using some of the new properties / classes. 

https://docs.google.com/document/d/1hey3yfQf4Se_N2jVi4bjgwHNb2-_pCBm4l5A2eEf_gk/edit

"relatedObjects": Moved to #44 therefore I will adjust the title here.

**Comment by tschleider** [comment]
Mapping got changed in the meanwhile, but the new mapping requires new classes and properties.

@mpuren : I cannot remember if you read the statistics yet, that I created in March or if we ever talked about it?

**Comment by rtroncy** [comment]
I have looked at the [mapping for the MET museum](https://docs.google.com/document/d/1hey3yfQf4Se_N2jVi4bjgwHNb2-_pCBm4l5A2eEf_gk/edit#) and in particular the mapping of the field `galleryInformation`. I'm also NOT in favor of including this in the KG at this stage of the project.
