### ISSUE TITLE
Document the URI policy being used in the knowledge graph

### ISSUE THREAD

**Issue by rtroncy** [silknow/converter#42]
We do create a number of URIs for identifying every object in the SILKNOW knowledge graph. The recipes for creating those URIs should be documented in a proper `URIPolicy.md` file in the root of the repo. 

Such a documentation will also help resolving issue #27

**Comment by tschleider** [comment]
[Here](http://data.silknow.org/sparql?default-graph-uri=&query=SELECT+count%28%3Fs%29+as+%3Fcount+%3Ft%0D%0AWHERE+%7B+%0D%0A++++++%3Fs+a+%3Ft%0D%0A%7D%0D%0AGROUP+BY+%3Ft+%0D%0AORDER+BY+DESC+%28%3Fcount%29&format=text%2Fhtml&timeout=0&debug=on) is the query that shows the count of all URI types used right now.

**Comment by rtroncy** [comment]
You should of course restrict this query to the useful graphs as opposed to query the entire triple store. For example, you can exclude the ontology and thesaurus and only query the museum graphs

**Comment by tschleider** [comment]
[Here](http://data.silknow.org/sparql?default-graph-uri=&query=SELECT+count%28%3Fs%29+as+%3Fcount+%3Ft%0D%0AWHERE+%7B+graph+%3Fg+%7B+%0D%0A++++++%3Fs+a+%3Ft%0D%0A%0D%0A%0D%0AFILTER+%28contains%28str%28%3Fg%29%2C+%22mad%22%29+%7C%7C+contains%28str%28%3Fg%29%2C+%22mtmad%22%29+%7C%7C+contains%28str%28%3Fg%29%2C+%22joconde%22%29+%7C%7C+contains%28str%28%3Fg%29%2C+%22imatex%22%29+%7C%7C+contains%28str%28%3Fg%29%2C+%22unipa%22%29+%7C%7C+contains%28str%28%3Fg%29%2C+%22risd%22%29+%7C%7C+contains%28str%28%3Fg%29%2C+%22vam%22%29+%7C%7C+contains%28str%28%3Fg%29%2C+%22met%22%29+%7C%7C+contains%28str%28%3Fg%29%2C+%22cer%22%29+%7C%7C+contains%28str%28%3Fg%29%2C+%22garin%22%29+%7C%7C+contains%28str%28%3Fg%29%2C+%22mfa%22%29%29%0D%0A%0D%0A%7D%7D%0D%0A%0D%0AGROUP+BY+%3Ft+%0D%0AORDER+BY+DESC+%28%3Fcount%29&format=text%2Fhtml&timeout=0&debug=on) the new query.

**Comment by rtroncy** [comment]
So, you see, this type of query helps to identify bugs :-)

- search why you have one occurrence of <http://data.silknow.org/title> and <http://data.silknow.org/html>
- is it normal to have a different count between E22 and D1? Should we not have an exact 1-1 relationship?
- do you really have this number (64811) as physical image files in the media server?
- why do you have 419 instances of ```foaf:Document```?

**Comment by tschleider** [comment]
>   search why you have one occurrence of http://data.silknow.org/title and http://data.silknow.org/html

I cannot find anything on that. I looked for "html" and "title" in the whole project and could not find anything. @pasqLisena do you have an idea where this could come from?
 
>   is it normal to have a different count between E22 and D1? Should we not have an exact 1-1 relationship?

There is a certain "reference" mechanism in Joconde that creates a second E22 per D1 at least in some cases. The difference from Joconde alone with this is 177. The remaining one comes from Garin actually. I did not code these parts, but I can revise them as part of solving the new issue #44 

>   do you really have this number (64811) as physical image files in the media server?

We have 65316 files on the media server. Dead external links still get a E38 class created so this number seems fine.

 
>   why do you have 419 instances of `foaf:Document`?

Same as above. @pasqLisena , any ideas?

**Comment by rtroncy** [comment]
> > do you really have this number (64811) as physical image files in the media server?
> 
> We have 65316 files on the media server. Dead external links still get a E38 class created so this number seems fine.

I don't understand this explanation. Once we crawl an image, an instance of E38 is generated. This instance will have systematically two locators for the media, a local link (always working) and the original link from the museum media server that may be dead soon after. But this does not explain why we have **less** instances of E38 than there are local media files. What am I missing?

**Comment by tschleider** [comment]
E38 is only generated during conversion not during the crawl and the crawl includes dead links, just as they are on the website or given by the API. So every E38 always has an external link that might have been always dead, even during the crawl (that's why I added schema:error to reflect that) and then in addition a local Silknow link, but only IF it was not dead during the crawl and we could download and copy it to the media server. Therefore there is a (slight) difference.

**Comment by rtroncy** [comment]
Thanks for the additional explanation. I previously thought that we always add at least one local image illustrating a record we have crawled but you are now saying this is not always the case! This should not be represented in the knowledge graph but this should be flagged in the output of the crawler somehow (maybe in a log, ideas welcome @ehrhart !)

**Comment by ehrhart** [comment]
The crawler already flags dead links with the `hasError` property in the JSON record file. For example, with Imatex:

```json
[{
  "id": "0000045452",
  "url": "http://imatex.cdmt.cat/fotografies/0000045452.jpg",
  "localFilename": "11935_1.jpg",
  "hasError": true
}]
```

**Comment by rtroncy** [comment]
Great! @ehrhart Can you count over all JSON records of all museum crawls the number of occurrences of ```"hasError": true```?  

@tschleider 65316 local images should already make 65316 instances of the E38 class. In addition, you should have a number of additional instances of E38 class for which you never got an image. However, you have only 64811 instances of E38. You're missing 505 + an unknown number. Or am I missing something ...

**Comment by pasqLisena** [comment]
>> why do you have 419 instances of foaf:Document?
>
> Same as above. @pasqLisena , any ideas?

Hey, this is a simple query!  -- [results](http://data.silknow.org/sparql?default-graph-uri=&query=select+*+where+%7B+%3Fs+a+foaf%3ADocument+%7D+limit+10&format=text%2Fhtml&timeout=0&debug=on)

```sparql
select * where { ?s a foaf:Document } limit 10
```

Those records are part of the GeoNames data

**Comment by ehrhart** [comment]
> Great! @ehrhart Can you count over all JSON records of all museum crawls the number of occurrences of "hasError": true?

`grep -lr '"hasError":true' ./**/records` gives me [747 occurrences](https://github.com/silknow/converter/files/4180020/hasError.txt).

**Comment by tschleider** [comment]
@pasqLisena : Oops :) and thanks

**Comment by pasqLisena** [comment]
>> search why you have one occurrence of http://data.silknow.org/title and http://data.silknow.org/html
>
> I cannot find anything on that. I looked for "html" and "title" in the whole project and could not find anything. @pasqLisena do you have an idea where this could come from?

It seems those cases come from the met data. -- [results](http://data.silknow.org/sparql?default-graph-uri=&query=SELECT+*%0D%0AWHERE+%7B%0D%0A++graph+%3Fg+%7B++%0D%0A%3Fs+%3Fp+%3Fq+.%0D%0A++++%3Fs+a+%3Chtml%3E%0D%0A%7D%0D%0A%7D%0D%0A&format=text%2Fhtml&timeout=0&debug=on)
```sparql
SELECT *
WHERE {
  graph ?g {  
?s ?p ?q .
    ?s a <html>
}
}
```

@tschleider Can you search in the met output? E.g. with
```
grep -lr '<html>' ./**/*.ttl
```

**Comment by tschleider** [comment]
@pasqLisena : thanks, but the output is empty

@rtroncy : I realise that I mixed up the image numbers in my head, so my explanation makes indeed no sense. I remember there are some redundant images in the wrong format on the server, I'll try to remove them.

**Comment by ehrhart** [comment]
> search why you have one occurrence of http://data.silknow.org/title and http://data.silknow.org/html

I did some quick search and the issue is in `./met/geonames/2935022.rdf`, which contains HTML data instead of RDF (I assume these files are generated from multiple request to geonames API and the API probably failed for this particular call)

Extract from `./met/geonames/2935022.rdf`:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd ">
<html>
<head>
<title>GeoNames</title>
...
<body>
...
<br><br><br><br>
<div style="margin:auto; width:500px; padding:40px; text-align:left" class="formTemplateClass">
ERROR: canceling statement due to statement timeout
</div>
...
```

Hope that helps.

**Comment by pasqLisena** [comment]
Thanks @ehrhart !
This is a weird TIMEOUT Geonames error, because for the rdf download there is no quota (while for the api yes).

A new run should clean this

**Comment by tschleider** [comment]
Ok I finished the [document](https://github.com/silknow/converter/blob/master/URI-patterns.md).

As discussed already, the remaning URI types come from GeoNames, shall I include them/explain them as well?

**Comment by tschleider** [comment]
Update with section on the image UUID

**Comment by tschleider** [comment]
Updated (Today) and improved  [document](https://github.com/silknow/converter/blob/master/URI-patterns.md).

@rtroncy  : Let me know if there is more to improve / add, otherwise I suggest to close this issue.

**Comment by rtroncy** [comment]
I will update the [URI pattern document](https://github.com/silknow/converter/blob/master/URI-patterns.md) and open new github issues when needed. Closing for now.
