### ISSUE TITLE
MET+Joconde: Reference mechanism can be implemented

### ISSUE THREAD

**Issue by tschleider** [silknow/converter#44]
These two datasets (MET and Joconde) refer to other objects, what we still need to reflect in the KG. 

Corresponding issue #4 needs to be reviewed and closed soon (after some confirmation), as its remaining parts should be treated in this issue

**Comment by tschleider** [comment]
We have a remaining discrepancy between Man_Made-Objects and Production (E22 and E12) of exactly 7 that I could track back to an old reference mechanism of Joconde. I deactivated it so the two numbers will be exactly equal after the next reconversion. From then I will add a new one that will not create new E22 Man_Made-Objects for records that are not crawled.

**Comment by rtroncy** [comment]
Revisiting this issue: do we have any E22_Man-Made_Object that is somehow related to another E22_Man-Made_Object in the KG? If so, what is the nature of the property that relates them?

From the [MET museum mapping](https://docs.google.com/document/d/1hey3yfQf4Se_N2jVi4bjgwHNb2-_pCBm4l5A2eEf_gk/edit), the field _relatedObjects_ seem to generate the creation of a `ecrm:E89_Propositional_Object` which is `ecrm:P129_is_about` the E22 but this is pretty useless as information.

Worst, the following SPARQL query ([results](https://data.silknow.org/sparql?default-graph-uri=&query=SELECT+%3Fg+%3Fx%0D%0AWHERE+%7B%0D%0A++GRAPH+%3Fg+%7B%3Fx+a+ecrm%3AE89_Propositional_Object%7D%0D%0A%7D&should-sponge=&format=text%2Fhtml&timeout=0&debug=on&run=+Run+Query+)) shows that only Joconde has related objects (and not MET for example!)

```
SELECT ?g ?x
WHERE {
  GRAPH ?g {?x a ecrm:E89_Propositional_Object}
}
```

**Comment by tschleider** [comment]
No update so far, as I didn't have the time. 
In general we have several datasets that mention identifier of related records. The nature of this relation is not really specified, I think.

- MET: The field "relatedObjects" is right now not getting converted.
- Joconde: The existing E89 does refer to itself, right now, not to another related object. I did not understand the nature of this mapping at first.

What is needed in any case is a mechanism that can generate the full URI of the related object based on the internal record ID. Eventually we need to revise the URI pattern for D1/E22 for this, because during conversion the converter goes through every file alone.

**Comment by rtroncy** [comment]
Following-up the February 5th, 2021 telecon, we agreed that we should use the the `P129_is about` property to relate the `E89_Propositional_Object` with the `E22_Man-Made_Object`.

Have the recent changes in the way we create UUID clarify how we will identify the E89 objects?

**Comment by tschleider** [comment]
Ok so now they are implemented and working. However, indeed the ID change has affected it a bit. From the ID MET is providing me I can only reconstruct the D1 UUID, wheras Joconde is providing us with the internal museum ID that we now use for E22 only:

Met:
https://data.silknow.org/describe/?url=http%3A%2F%2Fdata.silknow.org%2Fobject%2F6081a896-8b64-32f0-973d-74ba26cec730

Joconde:
https://data.silknow.org/describe/?url=http%3A%2F%2Fdata.silknow.org%2Fobject%2F1eca35fe-8e9c-3d12-a217-364ca41a21ec&sid=767

In cases of records that are referred to and that are not in the KG there will be NO new E22 generated, just their (theoretical) URI.
