### ISSUE TITLE
General: We need a property for sourcing the museum object in the Graph

### ISSUE THREAD

**Issue by tschleider** [silknow/converter#45]
Currently, the museum is just retrievable by its named graph URI, but not as a direct property inside the graph. Once we replace the internal UUID generation from filename to internal museum ID we also need an information about the original JSON file name inside the graph.

**Comment by pasqLisena** [comment]
What about [schema:publisher](https://schema.org/publisher) or [dcterms:publisher](http://purl.org/dc/terms/publisher) or [dcterms:creator](http://purl.org/dc/terms/creator) attached to the `E31_Document` entities?

**Comment by rtroncy** [comment]
+1 for using  [schema:publisher](https://schema.org/publisher) or [dcterms:publisher](http://purl.org/dc/terms/publisher)!

But why attaching this property to `E31_Document`? There is only the [Joconde museum that seems to have instances of this class](http://data.silknow.org/sparql?default-graph-uri=&query=select+*+%0D%0Awhere+%7B+%0D%0A+graph+%3Fg+%7B+%3Fs+a+ecrm%3AE31_Document+%7D%0D%0A+%3Fs+ecrm%3AP70_documents+%3Fo+.%0D%0A%7D&format=text%2Fhtml&timeout=0&debug=on). I would attach it to the `E22_Man-made_Object` entity.

**Comment by pasqLisena** [comment]
Well, formally the museum is not the publisher of the `E22_Man-made_Object` but of the record describing it. It is surprising to me that there is no `E31_Document` in general.

**Comment by rtroncy** [comment]
You're absolutely right, the museum should not be the publisher of the `E22_Man-made_Object` but of the `D1_Digital_Object` which is materializing the record (French _notice_)

**Comment by pasqLisena** [comment]
Ah right, Digital Object!

**Comment by tschleider** [comment]
We now have a property `dc:publisher` attached to D1 objects pointing to the museums identified by
http://data.silknow.org/organization/ + DATASET_NAME
