### ISSUE TITLE
E78 Collection and URI generation

### ISSUE THREAD

**Issue by pasqLisena** [silknow/converter#48]
We discovered (thanks @ehrhart) that there are multiple E78 Collection item [sharing the same label](https://data.silknow.org/sparql?default-graph-uri=&query=select+distinct+*+where+%7B+%3Fs+rdfs%3Alabel+%3Flabel+%3B+rdfs%3Alabel+%22European+Sculpture+and+Decorative+Arts+%2843%2C014%29%22+%7D&should-sponge=&format=text%2Fhtml&timeout=0&debug=on&run=+Run+Query+).

This is because the [URI generation](../URI-patterns.md) is made taking into account the Object id, while the Collection are by definition spanning multiple object.

The situation about the repetition is the following one ([results](https://data.silknow.org/sparql?default-graph-uri=&query=SELECT+%3Fg+%3Flabel+count%28distinct+%3Fs%29+as+%3Fcount+WHERE+%7B%0D%0A+GRAPH+%3Fg+%7B+%0D%0A++%3Fs+a+ecrm%3AE78_Collection%3B%0D%0A+++++rdfs%3Alabel+%3Flabel%0D%0A+%7D%0D%0A%7D+GROUP+BY+%3Fg+%3Flabel%0D%0AORDER+BY+%3Fg+%3Flabel&should-sponge=&format=text%2Fhtml&timeout=0&debug=on&run=+Run+Query+)):
```sparql
SELECT ?g ?label count(distinct ?s) as ?count WHERE {
 GRAPH ?g { 
  ?s a ecrm:E78_Collection;
     rdfs:label ?label
 }
}
GROUP BY ?g ?label
ORDER BY ?g ?label
```
This is impacting the development of the KG explorer.

### Proposal

I propose to add the Collection to the list of "special" classes for URI generation (so, together with Person and Place), and use a seed composed by:
- _source_ (e.g. "vam", the collection do not span across sources)
- _class_ (so the string "E78_Collection")
- _label_ (e.g. "Textiles and Fashion Collection")

This  will automatically merge those Collections by label in a single URI.

### Proposed tasks
- [x] Discover what are those numbers in the collections of MET, and understanding if e.g. "Asian Art (36,195)" and "Asian Art (36,215)" are referring to the same collection or not.
- [x] Implement the change in the URI pattern
- [x] Test and document this change

**Comment by tschleider** [comment]
Thanks for documenting this so well, I am on it to check if these numbers can be ignored or not. (We actually skip them for other Fields / Properties in MET)

**Comment by tschleider** [comment]
I checked the MET website and compared the number there with the same objects we have in the crawl and most are not identical. In fact, the MET website number is always a bit higher, but in a similar range I guess it's something like a count. 

What's more important is that regardless of the number, there is only a specific amount of departments, and even if objects in the JSON / TTL files have different numbers, on the website they all have the same ID if they have the same string! So Asian Art = Asian Art, e.g.

Therefore I suggest to just remove the parentheses from the string, maybe we should do this with all strings from Met.

**Comment by tschleider** [comment]
I followed your proposal and tested it with MET (changes will affect every dataset of course). I also remove the parentheses at the end of strings for MET. 

Seed is generated by: dataset name + class + collection label

Can you confirm that this is what you had in mind @pasqLisena ? If nobody else objects I will then proceed with uploading. Then we can all test and if it's fine I will modify the documentation.

Here an excerpt from 35782.ttl (MET):

```
<http://data.silknow.org/collection/9da6eaf6-44e5-312f-aeea-f952721bcd24>
        a                          ecrm:E78_Collection ;
        rdfs:label                 "Arms and Armor" ;
        ecrm:P106_is_composed_of   <http://data.silknow.org/object/13bc4dd1-a2d0-36c7-998b-1f8615203436> ;
        ecrm:P78_is_identified_by  "Arms and Armor" .
```

**Comment by pasqLisena** [comment]
I think yes!
So, basically the URI http://data.silknow.org/collection/9da6eaf6-44e5-312f-aeea-f952721bcd24 should appear in different files across MET dump

**Comment by tschleider** [comment]
Ok we got it now: 
https://data.silknow.org/describe/?url=http%3A%2F%2Ferlangen-crm.org%2Fcurrent%2FE78_Collection&sid=156

This shows that all E78 with the same label have the same URI, your initial query @pasqLisena  also shows that every label appears only once. If we are all happy with the result, I will add it to the URI policy file and close the issue.

**Comment by tschleider** [comment]
Tested again and documented, therefore closing.
