### ISSUE TITLE
MAD converter: complex regex parsing needed for production location/time

### ISSUE THREAD

**Issue by tschleider** [silknow/converter#5]
One field ("Création") contains several values, and some of them belong to time, some to place, some to something else. For the 'time' I can use some more regex, for the rest I have to see.

example: 
"label":"Création:","values":["France","1700-1730","Louis XIV (époq.)","Louis XV (époq.)"

**Comment by rtroncy** [comment]
This query gives a good account of the current situation ([results](https://data.silknow.org/sparql?default-graph-uri=&query=SELECT+DISTINCT+%3Fo+%3Flabel+%3Fprod+%3Fts+%3Floc%0D%0AWHERE+%7B%0D%0A++GRAPH+%3Chttp%3A%2F%2Fdata.silknow.org%2Fgraph%2Fmad%3E+%7B%0D%0A+++++%3Fo+a+ecrm%3AE22_Man-Made_Object+.%0D%0A++%7D%0D%0A++%3Fo+rdfs%3Alabel+%3Flabel+.%0D%0A++%3Fprod+ecrm%3AP108_has_produced+%3Fo+.%0D%0A++OPTIONAL+%7B+%3Fprod+ecrm%3AP4_has_time_span+%3Fts+.+%7D%0D%0A++OPTIONAL+%7B+%3Fprod+ecrm%3AP8_took_place_on_or_within+%3Floc+.+%7D%0D%0A%7D%0D%0A&should-sponge=&format=text%2Fhtml&timeout=0&debug=on&run=+Run+Query+)):

```
SELECT DISTINCT ?o ?label ?prod ?ts ?loc
WHERE {
  GRAPH <http://data.silknow.org/graph/mad> {
     ?o a ecrm:E22_Man-Made_Object .
  }
  ?o rdfs:label ?label .
  ?prod ecrm:P108_has_produced ?o .
  OPTIONAL { ?prod ecrm:P4_has_time_span ?ts . }
  OPTIONAL { ?prod ecrm:P8_took_place_on_or_within ?loc . }
}

```

As one can see, none of the objects from MAD have a production location or production time. The [mapping file of MAD](https://docs.google.com/document/d/1zpNE6iBl33PoqLD-xKutDzBjFxPBJvCWx5wZ-K-5b7o/edit) shows that the field name `Création` probably contains these information but needs complex parsing.
