### ISSUE TITLE
Possible Time span bug: "ca. 1855 (made)" appears very often

### ISSUE THREAD

**Issue by tschleider** [silknow/converter#51]
The following very precise query gives so many results, that it looks suspicious

```
select ?s where {
  ?s ecrm:P4_has_time-span / rdfs:label "ca. 1855 (made)" 
}
```

**Comment by tschleider** [comment]
@pasqLisena - Suggestion to close:
I checked through a lot of these digital objects, and checked their original JSON files. 
In every single case this date is exactly set like this, so this means no bug. 

Examples (look at rdfs:comment /P1 descriptions) :

https://data.silknow.org/describe/?url=http%3A%2F%2Fdata.silknow.org%2Fobject%2Fa38cd760-66a5-32cd-b22e-d1bb09b361dc

https://data.silknow.org/describe/?url=http%3A%2F%2Fdata.silknow.org%2Fobject%2F6c6e5455-0fb9-3274-befd-485b4a88c994

https://data.silknow.org/describe/?url=http%3A%2F%2Fdata.silknow.org%2Fobject%2F69d5b383-dd2d-320b-94a7-79b26c4ab1d7

**Comment by rtroncy** [comment]
The year [1855](https://en.wikipedia.org/wiki/1855) has been rich !
