### ISSUE TITLE
Use httpS for images base URL

### ISSUE THREAD

**Issue by ehrhart** [silknow/converter#57]
Images URLs should use httpS (supported by the media server) instead of plain http.

**References:**
* https://github.com/silknow/converter/blob/8bd86589ee24d34ab86c9ef4f4e3c0bd34bb911d/src/main/java/org/silknow/converter/entities/Image.java#L10
* https://github.com/silknow/converter/blob/ae9cbf9715b4f5d5377569b3e0f6154327dc1198/src/main/java/org/silknow/converter/converters/GarinConverter.java#L19

**Example:**
`http://silknow.org/silknow/media/imatex/20183_0.jpg` -> `https://silknow.org/silknow/media/imatex/20183_0.jpg`

**Comment by tschleider** [comment]
Done. 

See e.g. [Link](https://data.silknow.org/describe/?url=http%3A%2F%2Fdata.silknow.org%2Fimage%2F857ec056-d06b-3012-9ced-8fb9548b18ad&sid=492)
