### ISSUE TITLE
UNIPA: New dataset format required for proper conversion

### ISSUE THREAD

**Issue by tschleider** [silknow/converter#6]
The requirements for the (crawler+) converter is:

- We need one file per record

- the first column should contain the field labels, the second one the field values, nothing else

I have not taken care of the naming, but each file should be called like the collection and a number, like "cattedrale-di-palermo-1" for example. If they are named like this the files do  not need subfolders, they could all be in one "UNIPA" folder for example.

**Comment by tschleider** [comment]
Format is updated now, but we still need the images as separate files.

**Comment by tschleider** [comment]
All the XLSX files here are the records in the requested format, ready for the crawler to convert it to our JSON format and then for the converter to RDF. 
https://drive.google.com/drive/folders/1SdIfRxadqy3FbNkOG0fjkkjUUbMD6lp7

All images are in the required format on OwnCloud:
https://silknow.uv.es/owncloud/index.php/apps/files/?dir=/UNIPA&fileid=43

Therefore the issue can be closed.

**Comment by rtroncy** [comment]
I'm re-opening this issue, just to make sure that the next steps are clear.

You suggest that the crawler to be updated to convert from csv (https://drive.google.com/drive/folders/1SdIfRxadqy3FbNkOG0fjkkjUUbMD6lp7) to the common json format? Does this really help the converter? The alternative is for the converter to directly take as input this csv format (in addition to the common json). If the former solution is adopted, then an issue on the crawler must be created to do the crawling/converting from the google drive folder.

The images need to be served from http://silknow.eu/silknow/media/unipa/. I'm not sure this is the case currently.

**Comment by tschleider** [comment]
@rtroncy : 

@ehrhart  added this step already quite a while ago (see https://github.com/silknow/crawler/commit/7fb6eaef49727dae6ce441cb2dcb5e835888f9f0, https://github.com/silknow/crawler/commit/c0e9a556e52aa46a1d37bbf94c4e994e2dcf43fa or https://github.com/silknow/crawler/commit/8a7b70600203bd5ddfecfb9497e08a46a5724593). Our idea was indeed  to keep the converter code more consistent. The other way seems also good, but now we have a working solution already.

It's true that the images are not yet integrated, but I opened this issue because of the unique format of the UNIPA records and considered the issue with the images since one of your mails last week to be the same as in all the other cases for which we have https://github.com/silknow/converter/issues/13.

**Comment by rtroncy** [comment]
You're right, thanks for reminding the history. This issue can be closed then.
