### ISSUE TITLE
Mapped rights not correctly implemented (e.g. for Joconde)

### ISSUE THREAD

**Issue by tschleider** [silknow/converter#60]
Issue as stated by @ehrhart:

https://www.pop.culture.gouv.fr/notice/joconde/01390002506 
(KB link: https://data.silknow.org/object/533e9cc4-e996-3994-9008-34326e45fd1e).

I've checked the field in the record json file, it is this one:
```
{
  "label": "PHOT",
  "value": "© François Perrodin - utilisation soumise à autorisation"
}
```

however I cannot seem to find this information in the KB or in the ttl files.

**Comment by tschleider** [comment]
Fixed, will deploy to stage tomorrow.

**Comment by tschleider** [comment]
Deployed to stage

**Comment by tschleider** [comment]
[Example](https://ada-preprod.silknow.org/describe/?url=http%3A%2F%2Fdata.silknow.org%2Fobject%2F533e9cc4-e996-3994-9008-34326e45fd1e%2Fimage%2Fright)

**Comment by rtroncy** [comment]
A `E30_Right` is always attached to an `E38_Image`?

There can be only 1 instance of E30 for an image? I can imagine that there could be multiple rights, and in this case, the URI pattern should be thought to be different such as: https://data.silknow.org/object/[UUID]/image/right/[int]

**Comment by tschleider** [comment]
The suggested URI pattern is now followed, e.g. for the example already mentioned above: [Following the example above](https://data.silknow.org/object/533e9cc4-e996-3994-9008-34326e45fd1e/image/right/1)

There are several rights fields / values and some do indeed have several entries. 

I updated the URI policy, too.

**Comment by rtroncy** [comment]
Can you provide another example of an image having multiple rights?

If I summarize the full path: an `E38_Image` is `P104_applies_to` of a `E30_Right` which has a note / comment. Next, this E30_Right is P75_possessed_by a E39_Actor. How is the label of this actor being defined? Obviously, the label of https://data.silknow.org/actor/180bbe49-4e79-3614-b968-55d5f56ed09e should be "François Perrodin" and not "François Perrodin - utilisation soumise à autorisation". What is the issue tracking this problem? Issue #2?

**Comment by tschleider** [comment]
Actually I misread something, "Rights" is a field that is always given per record and not per image / there are never several rights. I therefore removed the integer counter again / also from the URI policy.

About the E39_Actor, yes right now we don't have another issue open about it than #2. I can double check if everything we discussed about E39 is in the comments of the issue tomorrow.

**Comment by rtroncy** [comment]
It seems to me that the `E30_Right` has to be attached to the `E38_Image` (and not to the `E22_Man-Made_Object`). This is what the mapping says, right?

Even if the field (in the original metadata) is unique, this does not prevent that, for example, two people (`E39_Actor`) are mentioning as holding the rights. Why do you say that it can only be a unique person?

**Comment by tschleider** [comment]
Actually the implementation for photo copyrights now follows pretty exactly the [mapping](https://docs.google.com/document/d/1_DMd0aF4aweBmBKBMV11aUYzttqGT2ecTFAAJ0vNT6E/edit#heading=h.vy2q0pvq298w)

E38_Image P138 represents E22_ Man-Made Object
E38_Image P104 is subject to E30_Right

Only difference is that P104 is called "applies to". E.g. [here](https://data.silknow.org/describe/?url=http%3A%2F%2Fdata.silknow.org%2Fobject%2F0b76878d-f8a8-3d38-8c4c-6da6ecdfd3e7%2Fimage%2Fright%2F&sid=707)

I checked a lot of Joconde records and they simply have one value and never multiple values for photo copyrights, either a person's name or a studio. Do you want me to grep all possible values here?

For what the mapping calls "copyright notice" we have multiple values, but it also follows the mapping to have one right and multiple possible holders: [Example](https://data.silknow.org/describe/?url=http%3A%2F%2Fdata.silknow.org%2Fobject%2F1e630c5e-6285-3d36-90f2-655a99dc5481%2Fright%2F&sid=707).

I just realised the mapping uses rather E40_Legal Body and it's implemented with E39_Actor. Do you want me to change something about this?
