### ISSUE TITLE
Address Knowledge Graph issues reported in D7.1

### ISSUE THREAD

**Issue by rtroncy** [silknow/converter#64]
The various issues reported in the[ Deliverable D7.1, section 5](https://drive.google.com/file/d/1pKLZyd86fbpDnBTDqc5hj3azdkCymQeM/view) should be addressed:

- check how to represent object dimensions when the record does not describe a SINGLE object but set of textiles
- check how construction and techniques are represented in the KG
- represent in a structured way warp and weft information which are available from the `P3_has_note` textual property
- check that we appropriately distinguish the production location from the storage location
- check the production location for the objects coming from Monreale (UNIPA)

**Comment by rtroncy** [comment]
Note: several points have been partially answered in [this email from @tschleider](https://lists.eurecom.fr/sympa/arc/silknow/2020-05/msg00111.html).

**Comment by tschleider** [comment]
>     * check how to represent object dimensions when the record does not describe a SINGLE object but set of textiles
In the mapping file it is in general suggested to eventually create several E22 Man-made object classes per record. Would it not be easier to ask somebody to re-structure the data, as we are dealing with only 29 sheets? I think it would then be more precise and would not bloat the converter.


>     * check how construction and techniques are represented in the KG
Fixed (see e-mail)


>     * represent in a structured way warp and weft information which are available from the `P3_has_note` textual property
I think there was a misunderstanding that should be clear after my e-mail.


>     * check that we appropriately distinguish the production location from the storage location
Ongoing discussion, I sent out a new mail just recently to suggest the mapping to be changed. 


>     * check the production location for the objects coming from Monreale (UNIPA)
The original value(s) say(s) "ignoto", therefore we treat it as empty. There is no bug here.

**Comment by tschleider** [comment]
Remaining issue(s) brought up in mail conversations with UNIPA (Georgia) and Lyon (Marie).

**Comment by tschleider** [comment]
For the mapping change, this was concerning dimensions, all (old) Unipa records have now a single dimension that can be parsed, the other dimensions were pushed to the textual fields. [Example](https://ada-preprod.silknow.org/describe/?url=http%3A%2F%2Fdata.silknow.org%2Fobject%2Fa253a8d5-dbe0-3764-b8cb-600de4b9403c&sid=399)

The other ongoing issue has been fixed as part of #65  (production place).
