### ISSUE TITLE
UNIPA: verify that all records have been converted and fix the production / storage location

### ISSUE THREAD

**Issue by rtroncy** [silknow/converter#65]
The query:
```
select distinct ?g count(distinct ?s) as ?nbObj
where {
  graph ?g {?s a ecrm:E22_Man-Made_Object}
}
group by ?g
order by desc(?nbObj)
```
shows that UNIPA [has 438 records in the KG](https://ada-preprod.silknow.org/sparql?default-graph-uri=&query=select+distinct+%3Fg+count%28distinct+%3Fs%29+as+%3FnbObj%0D%0Awhere+%7B%0D%0A++graph+%3Fg+%7B%3Fs+a+ecrm%3AE22_Man-Made_Object%7D%0D%0A%7D%0D%0Agroup+by+%3Fg%0D%0Aorder+by+desc%28%3FnbObj%29%0D%0A&should-sponge=&format=text%2Fhtml&timeout=0&debug=on&run=+Run+Query+) while the original datasets were composed of:

- 29 gsheet files provided in this [gdrive folder](https://drive.google.com/drive/folders/1gJYv1CbwqknUORdMhPU-BUwr-6lkZ5ki)
- 146 records (and 146 images) provided in March 2020 in this [dropbox folder](https://www.dropbox.com/sh/t6q9e1sqcfauxrs/AAA-34LrPSWJaIS_XhlM6G4pa?dl=0)
- 410 records (and 409 images) provided in September 2020 in this [dropbox folder](https://www.dropbox.com/sh/a8zzv22r59q67eq/AAB4SOAGf1byLFwakYkzbcYFa?dl=0)

where the sum makes **585 records**. @tschleider can you please explain where the discrepancy comes from?

Next, there is an issue related to the conversion of the production location versus the storage location. See [this email from Valeria](https://lists.eurecom.fr/sympa/arc/silknow/2020-12/msg00125.html) to implement the proper interpretation of the field names

**Comment by tschleider** [comment]
I checked all records, the data provided in September 2020 contains all data from March, therefore all numbers are correct: 
29 gsheet files + 409 records in the new format (there is one empty row in the JSON, therefore 409 not 410) = 438. 

I fixed a minor discrepancy described in the email exchange and wrote a mail last week in which I ask Marie and Pierre to adopt the mapping according to Valeria's suggestion. I will follow up on that.

**Comment by tschleider** [comment]
Changed the mapping, will deploy the reconverted files to stage tomorrow.

**Comment by tschleider** [comment]
Deployed to stage

**Comment by tschleider** [comment]
The change was concerning the production place, now all records have a place mapped correctly:

[Example](https://ada-preprod.silknow.org/describe/?url=http%3A%2F%2Fdata.silknow.org%2Fproduction%2F9b14a1d7-7ccf-3223-96d6-c9ba0ebceb57&sid=398)

**Comment by rtroncy** [comment]
A better test would be to check that NONE of the UNIPA records have a production place different than 'Sicily' (https://sws.geonames.org/2523118/) rather than a single example but I guess that this is the case!
