### ISSUE TITLE
Resolving JOKER and BATMAN or how to categorize objects

### ISSUE THREAD

**Issue by rtroncy** [silknow/converter#67]
See also the related issue: #35

As an interim solution, we have created those 2 ugly URIs:

- https://data.silknow.org/has_type_P2/1 (JOKER)
- https://data.silknow.org/has_type_P2/2 (BATMAN)

where JOKER and BATMAN are defined as a sum of possible types that one can find as value of `ecrm:P2_has_type`, see also [this google doc](https://docs.google.com/document/d/10Kht6Rv-_4iHshKOC_GR8rmKtcxtAX0ndw0XWxP8PcI/edit#).

From the experts point of view:

- JOKER is relatively consistent in indicating the category of the object ([results](https://data.silknow.org/sparql?default-graph-uri=&query=SELECT+DISTINCT+%3Fg+count%28%3Fv%29+as+%3Fnb+%3Fl+%3Fv+%0D%0AWHERE+%7B%0D%0A++GRAPH+%3Fg+%7B%0D%0A+++++%3Fo+a+ecrm%3AE22_Man-Made_Object+.%0D%0A++%7D%0D%0A++%3Ft+ecrm%3AP41_classified+%3Fo+.%0D%0A++%3Ft+ecrm%3AP2_has_type+%3Chttp%3A%2F%2Fdata.silknow.org%2Fhas_type_P2%2F1%3E+.%0D%0A++%3Ft+ecrm%3AP42_assigned+%3Fv+.%0D%0A++OPTIONAL+%7B%3Fv+skos%3AprefLabel+%3Fl%7D%0D%0A%7D%0D%0AGROUP+BY+%3Fg+%3Fv+%3Fl%0D%0AORDER+BY+DESC%28%3Fnb%29%0D%0A&should-sponge=&format=text%2Fhtml&timeout=0&debug=on&run=+Run+Query+)). The value is hence often linked to our [controlled vocabulary of categories](https://github.com/silknow/knowledge-base/blob/master/vocabularies/category/categories.ttl) even if it could be further improved.

```
SELECT DISTINCT ?g count(?v) as ?nb ?l ?v 
WHERE {
  GRAPH ?g {
     ?o a ecrm:E22_Man-Made_Object .
  }
  ?t ecrm:P41_classified ?o .
  ?t ecrm:P2_has_type <http://data.silknow.org/has_type_P2/1> .
  ?t ecrm:P42_assigned ?v .
  OPTIONAL {?v skos:prefLabel ?l}
}
GROUP BY ?g ?v ?l
ORDER BY DESC(?nb)
```

Regarding the modeling, [the approach proposed by Pierre](https://lists.eurecom.fr/sympa/arc/silknow/2020-12/msg00083.html) amounts to create the following path:
`?t ecrm:P41_classified ?o .`
`?t a silknow:Txx_Object_Type_Assignment .` (where `Txx_Object_Type_Assignment  rdfs:subClassOf E17_Type_Assignment`)
`?t silknow:Lxx_assigned_object_type ?v.` (where `Lxx_assigned_object_type rdfs:subPropertyOf P42_assigned`)

- BATMAN seems much broader ([results](https://data.silknow.org/sparql?default-graph-uri=&query=SELECT+DISTINCT+%3Fg+count%28%3Fv%29+as+%3Fnb+%3Fl+%3Fv+%0D%0AWHERE+%7B%0D%0A++GRAPH+%3Fg+%7B%0D%0A+++++%3Fo+a+ecrm%3AE22_Man-Made_Object+.%0D%0A++%7D%0D%0A++%3Ft+ecrm%3AP41_classified+%3Fo+.%0D%0A++%3Ft+ecrm%3AP2_has_type+%3Chttp%3A%2F%2Fdata.silknow.org%2Fhas_type_P2%2F2%3E+.%0D%0A++%3Ft+ecrm%3AP42_assigned+%3Fv+.%0D%0A++OPTIONAL+%7B%3Fv+skos%3AprefLabel+%3Fl%7D%0D%0A%7D%0D%0AGROUP+BY+%3Fg+%3Fv+%3Fl%0D%0AORDER+BY+DESC%28%3Fnb%29%0D%0A&should-sponge=&format=text%2Fhtml&timeout=0&debug=on&run=+Run+Query+)) but we should verify that we already capture the object category with the sole JOKER!

```
SELECT DISTINCT ?g count(?v) as ?nb ?l ?v 
WHERE {
  GRAPH ?g {
     ?o a ecrm:E22_Man-Made_Object .
  }
  ?t ecrm:P41_classified ?o .
  ?t ecrm:P2_has_type <http://data.silknow.org/has_type_P2/2> .
  ?t ecrm:P42_assigned ?v .
  OPTIONAL {?v skos:prefLabel ?l}
}
GROUP BY ?g ?v ?l
ORDER BY DESC(?nb)
```

Regarding the modeling, [the approach proposed by Pierre](https://lists.eurecom.fr/sympa/arc/silknow/2020-12/msg00083.html) amounts to create the following path:
`?t ecrm:P41_classified ?o .`
`?t a silknow:Txx_Object_Domain_Assignment .` (where `Txx_Object_Domain_Assignment  rdfs:subClassOf E17_Type_Assignment`)
`?t silknow:Lxx_assigned_domain_type ?v.` (where `Lxx_assigned_domain_type rdfs:subPropertyOf P42_assigned`)

If we would adopt this modeling, it is unclear what should be the value of the property P2_has_type attached to the Object_Type_Assignment or Object_Domain_Assignment.

**Comment by rtroncy** [comment]
Given the new version of the SILKNOW ontology, we can now do the last steps to close this issue. What remains to be done:

- [x] For JOKER, the following triples should instead be used:

```
?t ecrm:P41_classified ?o .
?t a silknow:T35_Object_Type_Assignment .
?t silknow:L1_assigned_object_type ?v. 

```
- [x] For BATMAN

```
?t ecrm:P41_classified ?o .
?t a silknow:T19_Object_Domain_Assignment .
?t silknow:L4_assigned_domain_type ?v. 

```
There is no need anymore to attach a `P2_has_type` to the `E17_Type_Assignment` (or its subclasses)

**Comment by tschleider** [comment]
Again I had troubles to implement the new classes. Also some of the discussed changes per email (namespace etc.) are not applied on OntoME, so I had to change some stuff manually. Except for that, the code seems to be working fine, should be fixed tomorrow:

[Example](https://ada-preprod.silknow.org/describe/?url=http%3A%2F%2Fdata.silknow.org%2Fobject%2F5eac50a8-74dd-381f-88f9-43ab08616042%2Fobject_domain_assignment%2F1&sid=397)

**Comment by rtroncy** [comment]
The SILKNOW ontology has finally been pushed in the repository, see https://github.com/silknow/knowledge-base/blob/master/ontology/silknow-v1.0.ttl. Note however that the URI of the classes and properties may change a bit, see this [discussion thread](https://lists.eurecom.fr/sympa/arc/silknow/2021-03/msg00105.html).

I suggest to bind <http://data.silknow.org/ontology/> to `silk` as a predefined prefix. I indicated this in https://github.com/silknow/knowledge-base/commit/92803a3b33b7db1e619a91303180374dad00dc51 but make sure that the ontology is actually loaded in the repository and maybe some deployment scripts need to be updated.

I do have a problem again with the complex URI pattern you're creating:

- <http://data.silknow.org/object/5eac50a8-74dd-381f-88f9-43ab08616042/object_domain_assignment/1> should be transformed into <http://data.silknow.org/object/5eac50a8-74dd-381f-88f9-43ab08616042/domain/1>
- <https://data.silknow.org/object/a695dfd4-15c9-3699-82d9-a7544b284375/object_type_assignment/1> should be transformed into <https://data.silknow.org/object/a695dfd4-15c9-3699-82d9-a7544b284375/category/1>

As usual, https://github.com/silknow/converter/blob/master/URI-patterns.md should be updated!

**Comment by tschleider** [comment]
Ontology properly integated and KG updated accordingly on production:

- https://data.silknow.org/object/5eac50a8-74dd-381f-88f9-43ab08616042/domain/1
- https://data.silknow.org/object/a695dfd4-15c9-3699-82d9-a7544b284375/category/1

URI policy will be updated, too, once I pushed all recent changes.

**Comment by rtroncy** [comment]
Do not forget to remove / delete https://github.com/silknow/converter/blob/master/src/main/resources/vocabulary/old.ttl as well as https://github.com/silknow/knowledge-base/tree/master/vocabularies/temp

**Comment by tschleider** [comment]
> Do not forget to remove / delete https://github.com/silknow/converter/blob/master/src/main/resources/vocabulary/old.ttl as well as https://github.com/silknow/knowledge-base/tree/master/vocabularies/temp

Removed them.

By the way about the new URI pattern: "https://data.silknow.org/object/UUID/category/{int}"
We already use "category" for the namespace of the type of objects vocabulary, e.g.: http://data.silknow.org/category/20

Is it not too close?

**Comment by rtroncy** [comment]
Yes, this is on purpose as one is the filler of the other!

**Comment by tschleider** [comment]
Updated the URI policy. Is there anything else to do?

**Comment by rtroncy** [comment]
This [commit](https://github.com/silknow/converter/commit/07918f61e739d1ad8eb0c971b384277562ef7356) indicates a wrong URI pattern so this needs to be modified.

There are still traces of [JOKER](https://data.silknow.org/has_type_P2/1) and [BATMAN](https://data.silknow.org/has_type_P2/2) that needs to be deleted. In general, this `has_type_P2` temporary vocabulary needs to be deleted if it is not needed anymore. On the other side, appropriate vocabularies need to be materialized and uploaded in the Knowledge Graph

**Comment by tschleider** [comment]
So as discussed I created a proper vocabulary for the Object Type and Object Domain distinction: 
https://github.com/silknow/converter/blob/master/src/main/resources/vocabulary/type_domain.ttl

This is only used as a look-up for the original string values instead of having it as hard-coded rules inside the main Converter.
However, for some reason there's always a weird bug when I introduce a new vocabulary with string2vocabulary that it cannot always properly read it for a few days (I guess it's a caching issue somewhere?), therefore I couldn't finish reconversion. It will hopefully be fixed by tomorrow. This should however not change anything about the actual KG. 

The URI pattern is also fixed (example follows tomorrow).
Was there anything else?

**Comment by rtroncy** [comment]
This [controlled vocabulary](https://github.com/silknow/converter/blob/master/src/main/resources/vocabulary/type_domain.ttl) is not ideal.

First, do not create entries at the top level at http://data.silknow.org/ ! The pattern is to insert a short name for the concept scheme before detailing the concepts that are part of this scheme! This will ease the dereferencing, otherwise, you're multiplying the number of rules to manage and the complexity.

Second, you will not re-define <http://data.silknow.org/SILKNOW> `foaf:Project` in every vocabulary!

Third, you provide alternative labels in Spanish while putting a `@en` language tag!

Fourth, why is this version 2.0 for this vocabulary?

**Comment by tschleider** [comment]
> First, do not create entries at the top level at http://data.silknow.org/ ! The pattern is to insert a short name for the concept scheme before detailing the concepts that are part of this scheme! This will ease the dereferencing, otherwise, you're multiplying the number of rules to manage and the complexity.

Yes, I admit I didn't know what's best to use here, because the patterns for this issues are like: 

    - https://data.silknow.org/object/5eac50a8-74dd-381f-88f9-43ab08616042/domain/1
    - https://data.silknow.org/object/a695dfd4-15c9-3699-82d9-a7544b284375/category/1

I thought about http://data.silknow.org/object_assignment/, but I was afraid things get ugly quickly again. Also, I am actually not loading this vocabulary into the triple store.

> Second, you will not re-define http://data.silknow.org/SILKNOW foaf:Project in every vocabulary!

Right, noted. That's a leftover of using the thesaurus converter, will remove it from (most) vocabularies.

> Third, you provide alternative labels in Spanish while putting a @en language tag!

Will fix this. 

> Fourth, why is this version 2.0 for this vocabulary?

Again, just an oversight, will be fixed.

**Comment by rtroncy** [comment]
> I thought about http://data.silknow.org/object_assignment/, but I was afraid things get ugly quickly again. Also, I am actually not loading this vocabulary into the triple store.

What about using http://data.silknow.org/assignment/? This is for E17 right? What other E17 assignments you do that are not domain or object category? The controlled vocabulary needs of course to be materialized and loaded.

**Comment by tschleider** [comment]
1. https://data.silknow.org/assignment/ exists now, new "assignment" vocabulary now loaded into triple store and used during conversion
2. Language tags are now correct
3. Version number is 1.0 
4. foaf:project part removed from vocabulary

[Example node](https://data.silknow.org/describe/?url=http%3A%2F%2Fdata.silknow.org%2Fobject%2Fb034e1c1-6bf8-3f8f-9e2e-aa4edf039edb%2Fdomain%2F1)

**Comment by rtroncy** [comment]
Actualy, I closed this too quickly! I'm confused: why do we need this [controlled vocabulary](https://data.silknow.org/assignment/) in the first place that defines only 2 concepts, while we already have them as classes and properties with https://github.com/silknow/knowledge-base/blob/master/vocabularies/ontology/silknow-v1.0.ttl#L221 and https://github.com/silknow/knowledge-base/blob/master/vocabularies/ontology/silknow-v1.0.ttl#L294 ?

**Comment by tschleider** [comment]
So this is now few months old so it could be that I worked on it before the new classes and properties were fully available.

That said, I use string2vocabulary to normalise all the strings and replaces them with these two URIs. I could have another look and eventually re-write it still.

**Comment by rtroncy** [comment]
The point is that we should not use anymore this controlled vocabulary since there are new classes and properties. This is the shape of the RDF that needs to be changed.

**Comment by tschleider** [comment]
So, shall I completely remove the string2vocabulary part and therefore restore all the original strings?
The alternative is to hard-code the string - property mappings without a controlled vocabulary

**Comment by rtroncy** [comment]
No, you need to use string2vocabulary as an intermediate step. But not to make use of a controlled vocabulary, but to replace the concept by a different graph shape, using the new classes and properties (that need to be instantiated). Work out on an example on paper, and everything will be clearer.

**Comment by tschleider** [comment]
As far as I know there is always a vocabulary needed to use string2vocabulary, otherwise I'd have to ask @pasqLisena .

**Comment by rtroncy** [comment]
You apparently didn't get the issue. You can run string2vocabulary with this useless vocab as an intermediary step, but this should not be the end goal. Ultimately, this is the output graph shape that needs to be changed with instanciations of the new classes (T19 and T35). Otherwise, what is the purpose of these classes?

**Comment by tschleider** [comment]
[Example taken from above ](https://data.silknow.org/object/a695dfd4-15c9-3699-82d9-a7544b284375/category/1)

I kept most of the mechanism actually untouched, but this "assignment" vocabulary is no longer uploaded, and P2_has_type is no longer instantiated and linked to it. 

There are technically remainders of this still online, but this is part of a small deployment issue that should be fixed by tomorrow. On it's own I would say this issue is solved.

**Comment by tschleider** [comment]
Made sure all remainders are removed as well, definitely solved now.
