### ISSUE TITLE
Update the URI pattern creation of a number of class instances

### ISSUE THREAD

**Issue by rtroncy** [silknow/converter#69]
See https://github.com/silknow/converter/blob/master/URI-patterns.md. I believe that the following changes should be done:

- [x] `crmdig:D1_Digital_Object`: currently, the URI pattern looks like http://data.silknow.org/graph/[graph-short-name]/[ID]. Instead, the URI pattern should simply be: http://data.silknow.org/object/[UUID]
- [x] `ecrm:E73_Information_Object`: currently, the URI pattern looks like https://data.silknow.org/informationobject/[UUID]. Instead, the URI pattern should simply be: http://data.silknow.org/object/[UUID]. Between, what is this instance supposed to be? I do have the same question for what does `ecrm:E89_Propositional_Object` represent? (looking at http://data.silknow.org/object/a8c5aa2b-9426-32e9-a632-496243adde61 and nearby does not tell me)
- [x] `ecrm:E9_Move`: we do not seem to have anymore any instances of this class. Is it normal?
- [x] `ecrm:E11_Modification`: currently, the URI pattern looks like http://data.silknow.org/modification/[UUID]. Instead,  the URI pattern should simply be: http://data.silknow.org/event/[UUID]. It seems that only GARIN and Imatex are providing instances of this class. The type seems to always be "restoration". In the case of Imatex, it would be good to extract the temporal information of the restauration event.
- [x] `ecrm:E14_Condition_Assessment`: [none of the links](https://data.silknow.org/sparql?default-graph-uri=&query=SELECT+DISTINCT+%3Fg+%3Fs+%3Flabel%0D%0AWHERE+%7B%0D%0A++GRAPH+%3Fg+%7B%0D%0A++++%3Fs+a+ecrm%3AE14_Condition_Assessment+.%0D%0A++%7D%0D%0A++OPTIONAL+%7B+%3Fs+rdfs%3Alabel+%3Flabel+%7D%0D%0A%7D&should-sponge=&format=text%2Fhtml&timeout=0&debug=on&run=+Run+Query+) I have clicked are dereferencable, why? What is the purpose of those instances?
- [x] `ecrm:E31_Document`: why do we create instances of this class in the first place? This seems relevant only for UNIPA?

**Comment by tschleider** [comment]
Changes pushed, but not yet reconverted /  uploaded:

- D1: Changed the URI pattern. Seed for UUID is filename + JSON-ID
- E73: Changed the URI pattern. Seed is as usual. It is used in the mapping for "Bibliography" and "Exhibition" mappings.
- E9: This class was systematically replaced by a new class that is still not available to us. I asked Marie to temporarily change it back to E9. In the meantime I removed the mapping, I will set it up again asap.
- E11: URI pattern changed. @pasqLisena : Unless it takes you, too much time, do you have a Regex pattern in mind for Strings like this (year not always at the end, sometimes in the middle etc.): "RESTAURACIÓ*" : "Cerdà Durà, Elisabet - 2010 -  / Fundació Abegg Stiftung. 1992 -" (3008-en.json)?
- E14: I'm on it, they will be dereferencable tomorrow.
- E31: It used to be in the mapping, but has been replaced now. Next time I reconvert and upload the KG they will be gone.

**Comment by rtroncy** [comment]
Don't forget to update https://github.com/silknow/converter/blob/master/URI-patterns.md accordingly.

**Comment by tschleider** [comment]
Changed the URI pattern doc.

**Comment by pasqLisena** [comment]
> E11: URI pattern changed. @pasqLisena : Unless it takes you, too much time, do you have a Regex pattern in mind for Strings like this (year not always at the end, sometimes in the middle etc.): "RESTAURACIÓ*" : "Cerdà Durà, Elisabet - 2010 - / Fundació Abegg Stiftung. 1992 -" (3008-en.json)?

All is possible, but what is the date here? How this will be represented?
These for me are 2 different restoration events:
- by [Elisabet Cerdà Durà](https://www.linkedin.com/in/elisabet-cerd%C3%A0-dur%C3%A0-09631662) in 2010
- by Fundació Abegg Stiftung in 1992

Do you have a longer list of example to understand if we can always split at that `/`?

**Comment by tschleider** [comment]
- E14 is dereferencable now, but this highlights that it's implemented incorrectly. The actual "condition" is not in the KG right now. I'm on it.

@pasqLisena : Thanks for having a look. Here the[ full query](https://data.silknow.org/sparql?default-graph-uri=&query=SELECT+DISTINCT+%3Fg+%3Fs+%3Fcomment%0D%0AWHERE+%7B%0D%0A++GRAPH+%3Fg+%7B%0D%0A++++%3Fs+a+ecrm%3AE11_Modification+.%0D%0A%0D%0A++%7D%0D%0A++OPTIONAL+%7B+%3Fs+rdfs%3Acomment+%3Fcomment+%7D%0D%0A%7D&should-sponge=&format=text%2Fhtml&timeout=0&debug=on&run=+Run+Query+) for all E11s (It's not that many).

**Comment by pasqLisena** [comment]
[Like this](https://data.silknow.org/sparql?default-graph-uri=&query=SELECT+DISTINCT+%3Fcomment+count%28distinct+%3Fs%29%0D%0AWHERE+%7B%0D%0A++GRAPH+%3Chttp%3A%2F%2Fdata.silknow.org%2Fgraph%2Fimatex%3E+%7B%0D%0A++++%3Fs+a+ecrm%3AE11_Modification+.%0D%0A%0D%0A++%7D%0D%0A++%3Fs+rdfs%3Acomment+%3Fcomment%0D%0A%7D+%0D%0AGROUP+BY+%3Fcomment%0D%0AORDER+BY+%3Fcomment&should-sponge=&format=text%2Fhtml&timeout=0&debug=on&run=+Run+Query+) is more visible.

So, from what I see, ` -  /` is a newline character.
When there is the information about "author" and date, it is always following this pattern (**_line type A_**):

    (.+)(?: -|,|.) (\d{4})(?: \((.+)\))?

Where group 1 is the author, 2 is the year, 3 is the (optional) comment.

Whatever is not following this pattern (**_line type B_**) it is a comment on what has been done during the restoration (and should simply be attached to the event as a note).

When there are more lines type A, we should create one E11 for each of them.
In these cases, in the string there isn't any line type B (so we do not need to link the comment to the right event).

@tschleider can I let you implement it?

**Comment by tschleider** [comment]
All changes implemented, will deploy them to stage tomorrow.

**Comment by tschleider** [comment]
Deployed to stage

**Comment by tschleider** [comment]
Examples: 
- [D1](https://ada-preprod.silknow.org/describe/?url=http%3A%2F%2Fdata.silknow.org%2Fobject%2F645ae680-04e7-3e15-bc9d-1e6f1bb68532&sid=393)
- [E73](https://ada-preprod.silknow.org/describe/?url=http%3A%2F%2Fdata.silknow.org%2Fobject%2Fbd8272af-8014-3551-94fd-1410d81435bd&sid=394)
- [ E11](https://ada-preprod.silknow.org/describe/?url=http%3A%2F%2Fdata.silknow.org%2Fevent%2F47d1e207-e68c-3310-870f-6ba8d892ad04&sid=394)
- [E14](https://data.silknow.org/assessment/024d15d4-a230-3f8f-b3c6-f2a2e00cd60e)
