### ISSUE TITLE
VAM: Interlinking Wikidata and VAM artists / works

### ISSUE THREAD

**Issue by tschleider** [silknow/converter#7]
See the property proposal at https://www.wikidata.org/wiki/Wikidata:Property_proposal/Victoria_and_Albert_Museum_name_ID and assess the usage of the property in Wikidata

**Comment by rtroncy** [comment]
The [property P6764](https://www.wikidata.org/wiki/Property:P6764) has landed in Wikidata and it concerns artists and makers or subjects of items in the collection of the Victoria and Albert Museum. Interlinking with Wikidata will already be dealt with in #2 thus closing here.
