### ISSUE TITLE
Encoding the internal museum ID properly

### ISSUE THREAD

**Issue by tschleider** [silknow/converter#73]
This is based on the following [e-mail conversation](https://lists.eurecom.fr/sympa/arc/silknow/2021-02/msg00086.html)

We agreed to not touch the UUID generation for objects, based on the JSON IDs, but we realised that the internal museum IDs are not / not fully represented in the KG and need to address this.

Results of all P2_has_types of E42 Identifier Assignment: [LINK](https://data.silknow.org/sparql?default-graph-uri=&query=select+distinct+%3Fg+count%28%3Fs%29+as+%3Fcount+%3Fo+%0D%0Awhere+%7B%0D%0A++GRAPH+%3Fg+%7B%0D%0A++++%3Fs+a+ecrm%3AE42_Identifier+.%0D%0A++++%3Fs+ecrm%3AP2_has_type+%3Fo+%7D%0D%0A%7D+GROUP+BY+%3Fg+%3Fo%0D%0AORDER+BY+desc%28count%28%3Fs%29%29&should-sponge=&format=text%2Fhtml&timeout=0&debug=on&run=+Run+Query+)

**Comment by tschleider** [comment]
I went through every converter and made sure that the internal museum number is now in the KG (if available) without touching the URI UUID generation.

I uploaded the fix to stage. Here an example from IMATEX: 
https://ada-preprod.silknow.org/describe/?url=http%3A%2F%2Fdata.silknow.org%2Fobject%2F79a4a7d4-0479-39df-a5ae-f93b99deb7dc%2Fid%2F2655&sid=383

**Comment by tschleider** [comment]
Now also on production:

https://data.silknow.org/object/79a4a7d4-0479-39df-a5ae-f93b99deb7dc/id/2655

**Comment by rtroncy** [comment]
Good, what about normalizing the `P2_has_type` values attached to `E42_Identifier_Assignment`?

**Comment by tschleider** [comment]
I normalised all P2 values of E42 according to the mail of @mpuren : [Link](https://lists.eurecom.fr/sympa/arc/silknow/2021-02/msg00093.html) 

Example from above again: https://data.silknow.org/object/79a4a7d4-0479-39df-a5ae-f93b99deb7dc/id/2655

I also went through every dataset and checked that we have implemented all existing museum IDs.

Next step should probably be to only show the `rdfs:label` value of all E42s that have P2 "Object Identifier" @rtroncy @ehrhart in ADASilk, right? Because right now we show the `dc:identifier` value of every E22 and this is not in all cases the internal museum object identifier that the domain experts expect.

**Comment by tschleider** [comment]
Since our last discussion this could be merged with #77. 

Internal Museum identifiers are now the value of dc:identifier of E22 and nowhere else. E42 and E15 are normally not instantiated anymore. Example:

http://data.silknow.org/object/ef3d3703-f96d-391d-af4c-15884e613281

Issue can be closed.
