### ISSUE TITLE
Pattern Unit: Mapping and parsing needs to be adjusted, new class T24 instantiated for matches with ID 444

### ISSUE THREAD

**Issue by tschleider** [silknow/converter#74]
Right now we do not have any Thesaurus matches with [ID 444 "Pattern Unit"](https://data.silknow.org/vocabulary/444), although we have this information in the datasets. 

Some changes in the mappings as well as of the parsing of some fields (e.g. Dimension) is necessary. For succesful matches we then need to implement and use the new class T24.

Original note:
"Marie will update the mapping file https://docs.google.com/document/d/1ziuh2EiLcuMYDNCn9SUnh4pgQJiH1BY3ZwGg7121SeM/edit# to show how to instantiate the T24 class. Thomas is exploring how often we are making use of http://data.silknow.org/vocabulary/444. Apparently, it is not done used yet in the KG. This value will typically be found in Dimensions, like Cloth area. @tschleider to make sure this field is also linkable to the thesaurus. We will also find occurrences of these terms in the description blob."

**Comment by rtroncy** [comment]
@tschleider I suggest you write an example as comment here, selecting a relevant record + excerpt of the metadata record that would need special parsing as well as expected output in Turtle making use of the T24 class. I'm looking for a complete example to assess the complexity of the solution to implement.

**Comment by tschleider** [comment]
I only found T24 in the mapping for VAM and Garin. I tried to implement it accordingly, but I was not sure where the Thesaurus link ends up. 

Here a link for a E22 of Garin, focus on the new "P58 has section definition" property, which shows how I ended up doing it: 

https://ada-preprod.silknow.org/describe/?url=http%3A%2F%2Fdata.silknow.org%2Fobject%2F1b30c7fe-fa06-3a23-a57a-24bdd567cb0d&sid=392

I implemented basic parsing for both Garin and VAM, but I might need to double-check that I got all cases.

As you might see if you follow the link to the new patter unit class, I had some trouble to properly implement them as well and need to fix this asap.

**Comment by rtroncy** [comment]
There are indeed obvious bugs in your implementation.

First, as usual, start by being clear in the URI pattern you're using. Can an object have **multiple** section definition? Probably! Therefore, the URI to identify them could be: http://data.silknow.org/object/[UUID]/pattern/[int]

Second, look at this [T24 entity](https://ada-preprod.silknow.org/describe/?url=http%3A%2F%2Fdata.silknow.org%2Fobject%2F1b30c7fe-fa06-3a23-a57a-24bdd567cb0d%2Fpattern_unit%2F&sid=392) you created, you added a dimension in the URI but you added a double '/'

Finally, what are your doubts now in term of implementations? When do you fail to recognize that you should instantiate a T24 class? What is actually the mechanism that triggers it?

**Comment by tschleider** [comment]
> First, as usual, start by being clear in the URI pattern you're using. Can an object have multiple section definition? Probably! Therefore, the URI to identify them could be: http://data.silknow.org/object/[UUID]/pattern/[int]

True, I double checked the data and indeed there can be up to 3 dimensions. I think it's actually best to extend @pasqLisena 's recent work on the dimension parsing in the case of VAM. 

> Second, look at this T24 entity you created, you added a dimension in the URI but you added a double '/'
That's a typo, already fixed.

> Finally, what are your doubts now in term of implementations? When do you fail to recognize that you should instantiate a T24 class? What is actually the mechanism that triggers it?

Well the mapping doesn't actually give me any property or position for the thesaurus link, that's why I use "P58 has section definition" for it. 

Right now it gets triggered if the words "repeat" (or a synonym) is part of the dimension field, as @mpuren explained it / as far as i understand it from the mappings.

**Comment by rtroncy** [comment]
I suggest you make a SPARQL query giving as much information as possible (graph, object URI, label, production place and time, material, technique) for the E22 objects that have now a `P58_has_section_definition` to a pattern unit with the details of the T24 so that @mpuren verifies that this is correct and perhaps even complete.

**Comment by tschleider** [comment]
I implemented now another mechanism that builds up upon @pasqLisena  great work on the existing dimension parsing for VAM: 
https://data.silknow.org/describe/?url=http%3A%2F%2Fdata.silknow.org%2Fobject%2F89ac6c8c-4637-3854-931f-7984e492939b&sid=762

The only other datasets for which I could find mappings with pattern units was Garin, but it only has a single dimension here each time (don't know if it's the length or width): 

- Garin: 
https://data.silknow.org/describe/?url=http%3A%2F%2Fdata.silknow.org%2Fobject%2Fe54f61ec-b24c-3acb-9c81-fa785c3fddd2&sid=763

**Comment by rtroncy** [comment]
In [this example](http://data.silknow.org/object/89ac6c8c-4637-3854-931f-7984e492939b), there are first typos. Look at the values of the http://erlangen-crm.org/current/P58_has_section_definition property, this should be:
http://data.silknow.org/object/89ac6c8c-4637-3854-931f-7984e492939b/dimension/pattern/1 and http://data.silknow.org/object/89ac6c8c-4637-3854-931f-7984e492939b/dimension/pattern/2 (i.e. remove de double slash after /dimension/)

Second, you're not instantiating the T24 class, don't you?

**Comment by tschleider** [comment]
- I fixed the typo.
- I used T24 as value for rdf:type as follows: http://data.silknow.org/ontology/T24 . Is there a better way to use it? I kept this whole /dimension/ pattern as i re-use some of the dimension parsing, because ultimately we're dealing with a dimension (plus unit, e.g. cm) here.

**Comment by rtroncy** [comment]
I guess this will be visible once you're reloading the graph (I'm checking this [example](https://data.silknow.org/object/89ac6c8c-4637-3854-931f-7984e492939b)).

Regarding the information we are encoding, at the moment, we are mixing different type of values for the property `ecrm:P58_has_section_definition` attached to the E22 object:

- we provide the uri of a concept: https://data.silknow.org/vocabulary/444
- we provide structured information such as instances of the new http://data.silknow.org/ontology/T24 classes like https://data.silknow.org/object/89ac6c8c-4637-3854-931f-7984e492939b/dimension/pattern/1 and https://data.silknow.org/object/89ac6c8c-4637-3854-931f-7984e492939b/dimension/pattern/2

See also this query ([results](https://data.silknow.org/sparql?default-graph-uri=&query=select+distinct+*+%0D%0Awhere+%7B%0D%0A+graph+%3Fg+%7B+%3Fo+a+ecrm%3AE22_Man-Made_Object+.+%7D%0D%0A+%3Fo+ecrm%3AP58_has_section_definition+%3Fv+.%0D%0A+optional+%7B+%3Fv+a+%3Ftype+%7D%0D%0A%7D%0D%0Aorder+by+%3Fo&format=text%2Fhtml&should-sponge=&timeout=0&signal_void=on)):
```
select distinct * 
where {
 graph ?g { ?o a ecrm:E22_Man-Made_Object . }
 ?o ecrm:P58_has_section_definition ?v .
 optional { ?v a ?type }
}
order by ?o
```

What is the purpose of keeping the skos Concept? Why not deleting the triple <object> ecrm:P58_has_section_definition <https://data.silknow.org/vocabulary/444>

**Comment by tschleider** [comment]
I removed P58 (for now), will be visible after the next conversion. I thought it was mandatory to use it, but I was just simply confused how to represent it perfectly between having it as both class and thesaurus concept.

**Comment by tschleider** [comment]
It's removed: https://data.silknow.org/object/89ac6c8c-4637-3854-931f-7984e492939b
