### ISSUE TITLE
Mappings and converters for new datasets: Status

### ISSUE THREAD

**Issue by tschleider** [silknow/converter#75]
**Artic** 

- Mapping: Done
- Converter: Done

**Gallica**

- Mapping: [Done](https://docs.google.com/document/d/18lPImagw1GZrHuL2H5aj8nxzK9A4rK90a-q2cMALVRg/edit)
- Converter: Almost

Remaining discussion:
- @mpuren: I had to use FRBRoo because the textile samples are glued into a register, and some of the metadata relate to this "catalogue" of samples. Feel free to comment on the table if you see any problems. 

- @rtroncy: This may cause problems indeed and we will not attempt to visualize this information. What FRBRoo classes / properties do you use? We will not aim to represent the book itself, right? 

**Saint-Etienne**

- Mapping: Under Review
- Converter: Almost

**Europeana**

- Mapping: [Done](https://docs.google.com/document/d/1MgY5T0X6zMYy52jrBZdUbywGGHq_6EAVMgNQuJzMpcs/edit?usp=sharing)
- Converter: Not done*

*We expect some duplicate records with some existing datasets. Therefore we need to create a mechanism to prevent this / collapse them correctly.

**Comment by tschleider** [comment]
Update:
- Europeana: done*
 *Lacks the mechanism to make sure there are no duplicate records
- Gallica: a first usable version done, but without FRBRoo and some interpretations of the mapping as it's really different than usual

EDIT: 
- Removed Gallica again, due to unclear mapping status with FRBRoo

**Comment by tschleider** [comment]
Update: 

- **El Tesoro** is in the KG now as both the files and the mapping exists
- Mapping for Gallerie degli Uffizi exists too, but not the files yet

**Comment by tschleider** [comment]
Update: 

We agreed that we ignore the mentioned  but not yet integrated dataset except Europeana, Saint-Etienne and Louvre (previously not mentioned).

**Louvre**
- Mapping: done
- Converter: done
- Upload: done

**Europeana**
- Mapping: done
- Converter: done except for the mechanism to remove / avoid duplicate records in the KG
- Mechanism for duplicates: @ehrhart and me found a possibility to identify duplicates and the converter has been changed accordingly. However, we need another sparql script on top of this, not done yet. 

**Saint-Etienne**
- Mapping: It's still under review, but there have been recent changes
- Converter: Cannot be completed without the mapping

Summary of all other mentioned datasets:

**Artic**
- Mapping: Done
- Converter: Done
- Upload: Done

**El Tesoro**
- Mapping: Done
- Converter: Done
- Upload: Done

**Gallica**
_Will not be used / converted!_

**Gallerie degli Uffizi**
_Will not be used / converted!_

**Comment by rtroncy** [comment]
Thanks for the update. Can you

- indicate what needs to be yet reviewed for the mappings for St Etienne?
- provide details on the SPARQL patch you need to apply to make sure there is no duplicates from Europeana?

**Comment by tschleider** [comment]
- Haven't had a look at St. Etienne since July but what I meant was that Lyon told me it's not ready and last time I checked (July) Pierre was still working on it.
- I haven't finished the script, I'll do this asap and update this issue here. We basically made sure tha the format of the Europeana record ID is compatible with the other museum so that a script can remove duplicates.

**Comment by rtroncy** [comment]
I think you should email back Pierre to know what the status is precisely. We must have data from St Etienne for the review.

**Comment by tschleider** [comment]
Pierre confirmed that it's final now, I'll continue to work on it.

**Comment by tschleider** [comment]
I am done with the most common classes / properties and images for St. Etienne: 

[Example](https://data.silknow.org/describe/?url=http%3A%2F%2Fdata.silknow.org%2Fobject%2F23857bc3-314e-32d3-94db-2e77d3e85253)

[Image](https://data.silknow.org/describe/?url=http%3A%2F%2Fdata.silknow.org%2Fimage%2F9748e413-13ac-32a0-a78b-d1a7cf4cafae)

It will be finished this week

**Comment by rtroncy** [comment]
What is now the status?

**Comment by tschleider** [comment]
I worked on it, but I ran again into issues with the format that need to fixed first so I spend more time on the other issues first.

**Comment by tschleider** [comment]
**St. Etienne**

    Mapping: Done
    Converter: Done
    Upload: Done

I realised there was no progress on the script to remove duplicates for Europeana, this still needs to be done.

**Comment by ehrhart** [comment]
@rtroncy I've [added a patch](https://github.com/silknow/knowledge-base/commit/82366d39988e90e19b8c35c1229ed13a4da67fcb) to delete duplicates from Europeana based on their identifier.

Europeana data has been converted with https://github.com/silknow/converter/commit/fd83d9102789d442beeadd530487e82540ec0ac2 and deployed to the KB.

In total, we have 195 objects in the dump, of which 122 are duplicates. We have [73 objects](https://ada.silknow.org/object?graph=http%3A%2F%2Fdata.silknow.org%2Fgraph%2Feuropeana&sort=) left after deduplication.

**Comment by rtroncy** [comment]
Excellent! Do you think we can close this issue?
Do we have now: Artic + Europeana + St Etienne + El Tesoro + Louvre dumps and loaded?

**Comment by ehrhart** [comment]
We have data from [Artic](https://ada.silknow.org/object?graph=http%3A%2F%2Fdata.silknow.org%2Fgraph%2Fartic&sort=), [Europeana](https://ada.silknow.org/object?graph=http%3A%2F%2Fdata.silknow.org%2Fgraph%2Feuropeana&sort=), [St Etienne](https://ada.silknow.org/object?graph=http%3A%2F%2Fdata.silknow.org%2Fgraph%2Fmusee-st-etienne&sort=), [El Tesero](https://ada.silknow.org/object?graph=http%3A%2F%2Fdata.silknow.org%2Fgraph%2Fel-tesoro&sort=), and [Louvre](https://ada.silknow.org/object?graph=http%3A%2F%2Fdata.silknow.org%2Fgraph%2Flouvre&sort=).

We can close this issue.
