### ISSUE TITLE
New SILKNOW Ontology

### ISSUE THREAD

**Issue by tschleider** [silknow/converter#76]
https://ontome.dataforhistory.org/namespace/36

I don't have access to the newest version beyond an RDF export directly from OntoME. Several issues depend on new classes / properties from the new ontology.

From Slack:
"@rtroncy needs to push the latest version of the SILKNOW ontology in the repo"

**Comment by rtroncy** [comment]
Resolve in https://github.com/silknow/knowledge-base/commit/cf7825dd82626ec6a0a0a76b89cadc3bd66211a0
