### ISSUE TITLE
URI pattern is not respected for E17 type assignment

### ISSUE THREAD

**Issue by rtroncy** [silknow/converter#79]
The [URI Design Pattern](https://github.com/silknow/converter/blob/master/URI-patterns.md) states:
`E17_Type_Assignment | object | /type/{progressive int}`

However, this is not respected as one can see from this [link](https://data.silknow.org/describe/?url=http%3A%2F%2Ferlangen-crm.org%2Fcurrent%2FE17_Type_Assignment) where URL are like https://data.silknow.org/object/53cff18e-0dee-3f63-b306-52b9817d5d71/type_assignment/1 instead of https://data.silknow.org/object/53cff18e-0dee-3f63-b306-52b9817d5d71/type/1. This needs to be changed.

**Comment by tschleider** [comment]
I changed it, will be gone soon after the next conversion

**Comment by tschleider** [comment]
Done:

https://data.silknow.org/object/53cff18e-0dee-3f63-b306-52b9817d5d71/type/1
