### ISSUE TITLE
MTMAD: Most fields require complex parsing/entity recognition

### ISSUE THREAD

**Issue by tschleider** [silknow/converter#9]
Only two fields can be properly parsed with regex right now ("Dimensions" and "Forme de la citation"), the other ones need to be combined into one text note for now/as a workaround, until we try something more powerful like entity linking/recognition etc.

**Comment by rtroncy** [comment]
The `ecrm:P3_has_note` values attached to the object from this museum are a perfect candidate to try extensively Wikifier, see also #63

**Comment by rtroncy** [comment]
Close, since we have issue #63
